#!/usr/bin/env python3
"""GARS-authored single-cell QC + clustering wrapper — sub-stage 02.02 for scrnaseq.

The sibling of `rnaseq-de`: where that turns a bulk count matrix into differential
expression, this turns the `h5ad` produced by 02.01 into a filtered, clustered, annotated
AnnData object with per-cluster markers.

**This is where cell-level checks can honestly live.** The 02.01 wrapper is stdlib-only and
cannot open an HDF5 file, so its exit gate can only prove that every sample produced a matrix.
Here the analysis runs under `gars-bio`, so it can count cells — and it writes a machine-
readable `run/summary.json` whose numbers this stdlib wrapper then checks **against the
samplesheet**, an independent source. A summary that is merely self-reported and trusted would
gate nothing.

Division of labour, same as every 0028 wrapper: this file is stdlib-only and runs on stock
python; the analysis itself is a GENERATED script (`scripts/run_scrna.py`) executed under
`$GARS_PY` via the generated `submit.sh`. Clustering a real matrix is not login-node work
(decisions 0005, 0027), so it is sbatch work, always.

  check    validates config thresholds, that the resolved h5ad exists, and that the analysis
           environment actually carries scanpy/leidenalg -- reported as a NAMED preconditions
           failure, never a raw ImportError (the rule in assay_stage_skill_map.md).
  prepare  re-validates, then writes scripts/run_scrna.py, submit.sh and the reproducibility
           bundle. Deterministic bytes.
  collect  the exit gate: markers table's first column is `gene` and populated (the 0010
           defect class), every samplesheet sample present in summary.json with cells > 0,
           cluster count > 0, the processed object and figures real.

Input `--h5ad` is the PATH the router resolved by artifact type
(`_system/resolve_artifact.py`); this wrapper never searches for it.

Runs on stock python 3.6.8, stdlib only.
"""

import argparse
import csv
import datetime
import json
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
import workspace as ws          # noqa: E402
import wrapperlib as wl         # noqa: E402
from wrapperlib import (EXIT_OK, EXIT_FAILURE, EXIT_REFUSED, EXIT_USAGE,   # noqa: E402
                        emit, fail)

WORKSPACE = Path(__file__).resolve().parents[3]

ASSAY = "scrnaseq"
SUBSTAGE = "02_scrna-qc-cluster"

# The packages the generated analysis imports. Named here so `check` can refuse by name.
ANALYSIS_IMPORTS = ("scanpy", "anndata", "leidenalg", "sklearn", "matplotlib", "pandas",
                    "numpy")

REQUIRED_KEYS = ("qc.min_genes", "qc.min_cells", "qc.max_mito_pct", "n_hvg",
                 "cluster_resolution", "compute.partition", "compute.time",
                 "compute.cpus", "compute.mem")

# The analysis, generated verbatim into scripts/run_scrna.py at prepare time. A template
# string rather than a shipped file so the wrapper is one self-contained unit and the script
# version is pinned by the template version in the manifest. The script takes no arguments and
# embeds its exact inputs -- reproducible by `python run_scrna.py` alone.
RUN_SCRNA_TEMPLATE = '''#!/usr/bin/env python
"""Single-cell QC and clustering for {project}/{assay}, generated by the scrna-qc-cluster
wrapper. Do not hand-edit: regenerate with `prepare`.

Every threshold below came from _config/{assay}.yaml. They are RECORDED in summary.json
alongside the numbers they produced, so a reader can see what was filtered and why.
"""
import json
import os

import numpy as np
import scanpy as sc
import matplotlib
matplotlib.use("Agg")

IN_H5AD = "{h5ad}"
OUT = "{out}"
MIN_GENES = {min_genes}
MIN_CELLS = {min_cells}
MAX_MITO_PCT = {max_mito}
N_HVG = {n_hvg}
RESOLUTION = {resolution}
MITO_PREFIX = "{mito_prefix}"

os.makedirs(os.path.join(OUT, "tables"), exist_ok=True)
os.makedirs(os.path.join(OUT, "figures"), exist_ok=True)
os.makedirs(os.path.join(OUT, "data"), exist_ok=True)

sc.settings.figdir = os.path.join(OUT, "figures")
sc.settings.verbosity = 1

adata = sc.read_h5ad(IN_H5AD)
adata.var_names_make_unique()
n_cells_in, n_genes_in = int(adata.n_obs), int(adata.n_vars)

# The sample label. nf-core/scrnaseq's combined matrix carries it in .obs; if it does not,
# the whole object is one sample and is labelled as such rather than guessed.
sample_col = None
for candidate in ("sample", "batch", "library_id"):
    if candidate in adata.obs.columns:
        sample_col = candidate
        break
if sample_col is None:
    adata.obs["sample"] = "all"
    sample_col = "sample"
adata.obs[sample_col] = adata.obs[sample_col].astype(str)

# --- QC ------------------------------------------------------------------------------------
adata.var["mito"] = adata.var_names.str.upper().str.startswith(MITO_PREFIX)
sc.pp.calculate_qc_metrics(adata, qc_vars=["mito"], percent_top=None,
                           log1p=False, inplace=True)

cells_before = {{s: int(n) for s, n in
                 adata.obs[sample_col].value_counts().items()}}

sc.pp.filter_cells(adata, min_genes=MIN_GENES)
sc.pp.filter_genes(adata, min_cells=MIN_CELLS)
adata = adata[adata.obs["pct_counts_mito"] < MAX_MITO_PCT].copy()

cells_after = {{s: int(n) for s, n in
                adata.obs[sample_col].value_counts().items()}}

if adata.n_obs == 0:
    raise SystemExit(
        "every cell was filtered out (min_genes=%s, max_mito_pct=%s). This is a result to "
        "report, not a threshold to lower." % (MIN_GENES, MAX_MITO_PCT))

# --- normalise, HVG, PCA, neighbours, clusters ----------------------------------------------
adata.layers["counts"] = adata.X.copy()
sc.pp.normalize_total(adata, target_sum=1e4)
sc.pp.log1p(adata)
n_hvg = min(N_HVG, max(1, adata.n_vars - 1))
sc.pp.highly_variable_genes(adata, n_top_genes=n_hvg)
adata.raw = adata
adata = adata[:, adata.var.highly_variable].copy()
sc.pp.scale(adata, max_value=10)

n_comps = int(min(50, max(2, min(adata.n_obs, adata.n_vars) - 1)))
sc.tl.pca(adata, n_comps=n_comps)
sc.pp.neighbors(adata, n_neighbors=int(min(15, max(2, adata.n_obs - 1))), n_pcs=n_comps)
sc.tl.umap(adata)
sc.tl.leiden(adata, resolution=RESOLUTION, key_added="leiden", flavor="igraph",
             n_iterations=2, directed=False)

n_clusters = int(adata.obs["leiden"].nunique())

# --- markers ---------------------------------------------------------------------------------
# Written with the identifier column FIRST and named `gene`. The bulk sibling shipped a table
# of anonymous genes once (decision 0010); the exit gate checks this column by content.
markers_path = os.path.join(OUT, "tables", "cluster_markers.csv")
if n_clusters > 1:
    sc.tl.rank_genes_groups(adata, "leiden", method="wilcoxon")
    res = adata.uns["rank_genes_groups"]
    groups = list(res["names"].dtype.names)
    with open(markers_path, "w") as fh:
        fh.write("gene,cluster,score,logfoldchange,pval,pval_adj\\n")
        for g in groups:
            for i in range(len(res["names"][g])):
                fh.write("%s,%s,%.6g,%.6g,%.6g,%.6g\\n" % (
                    res["names"][g][i], g, res["scores"][g][i],
                    res["logfoldchanges"][g][i], res["pvals"][g][i],
                    res["pvals_adj"][g][i]))
else:
    # One cluster: there is nothing to contrast it against. An empty-but-headed table is
    # honest; inventing a comparison would not be.
    with open(markers_path, "w") as fh:
        fh.write("gene,cluster,score,logfoldchange,pval,pval_adj\\n")

# --- figures ----------------------------------------------------------------------------------
sc.pl.umap(adata, color="leiden", show=False, save="_clusters.png")
sc.pl.violin(adata, ["n_genes_by_counts", "total_counts", "pct_counts_mito"],
             jitter=0.4, multi_panel=True, show=False, save="_qc.png")

adata.write_h5ad(os.path.join(OUT, "data", "processed.h5ad"))

# --- the machine-readable summary the exit gate checks ------------------------------------------
# Cross-checked by the wrapper against the SAMPLESHEET, not trusted on its own.
summary = {{
    "n_cells_in": n_cells_in,
    "n_genes_in": n_genes_in,
    "n_cells_out": int(adata.n_obs),
    "n_genes_out": int(adata.n_vars),
    "n_clusters": n_clusters,
    "cells_before_qc": cells_before,
    "cells_after_qc": cells_after,
    "thresholds": {{"min_genes": MIN_GENES, "min_cells": MIN_CELLS,
                    "max_mito_pct": MAX_MITO_PCT, "n_hvg": n_hvg,
                    "resolution": RESOLUTION, "mito_prefix": MITO_PREFIX}},
}}
with open(os.path.join(OUT, "summary.json"), "w") as fh:
    json.dump(summary, fh, indent=2, sort_keys=True)

with open(os.path.join(OUT, "report.md"), "w") as fh:
    fh.write("# Single-cell QC and clustering — {project}\\n\\n")
    fh.write("Input: `%s`\\n\\n" % IN_H5AD)
    fh.write("| Measure | Value |\\n|---|---|\\n")
    fh.write("| Cells in | %d |\\n" % n_cells_in)
    fh.write("| Cells after QC | %d |\\n" % adata.n_obs)
    fh.write("| Genes in | %d |\\n" % n_genes_in)
    fh.write("| Highly variable genes used | %d |\\n" % adata.n_vars)
    fh.write("| Clusters | %d |\\n\\n" % n_clusters)
    fh.write("Thresholds: min_genes=%s, min_cells=%s, max_mito_pct=%s, resolution=%s\\n\\n"
             % (MIN_GENES, MIN_CELLS, MAX_MITO_PCT, RESOLUTION))
    fh.write("Per-sample cells retained:\\n\\n| Sample | Before | After |\\n|---|---|---|\\n")
    for s in sorted(cells_before):
        fh.write("| %s | %d | %d |\\n" % (s, cells_before[s], cells_after.get(s, 0)))

print(json.dumps(summary, indent=2, sort_keys=True))
'''


def paths_for(project):
    return {"substage": project / "02_bioinformatics" / ASSAY / SUBSTAGE,
            "config": project / "_config" / ("%s.yaml" % ASSAY),
            "samplesheet": project / "01_samplesheets" / ("%s_samplesheet.csv" % ASSAY)}


def analysis_python():
    """The interpreter the generated script runs under, from gars-env.sh's $GARS_PY."""
    import os
    return os.environ.get("GARS_PY", "python3")


def check_analysis_env(fails):
    """Refuse by NAME when the analysis environment lacks a package.

    The assay map's rule: a sub-stage that finds a requirement missing reports it as a
    preconditions failure naming the requirement, rather than surfacing a raw ImportError an
    hour into a Slurm job. `gars-bio` carries anndata but NOT scanpy or leidenalg as shipped;
    adding them is a pinned environment change (environment.md forbids installing on the fly).
    """
    py = analysis_python()
    # `import importlib` alone does NOT bring in importlib.util -- the submodule must be
    # imported explicitly, and the first version of this probe crashed on exactly that.
    probe = ("import importlib.util,sys;"
             "missing=[m for m in %r if importlib.util.find_spec(m) is None];"
             "sys.stdout.write(','.join(missing))" % (list(ANALYSIS_IMPORTS),))
    try:
        out = subprocess.run([py, "-c", probe], stdout=subprocess.PIPE,
                             stderr=subprocess.PIPE)
    except OSError as exc:
        fails.append(fail("preconditions",
                          "cannot run the analysis interpreter %r: %s. It comes from "
                          "$GARS_PY via _system/gars-env.sh." % (py, exc)))
        return
    if out.returncode != 0:
        fails.append(fail("preconditions",
                          "the analysis interpreter %r could not be probed: %s"
                          % (py, out.stderr.decode("utf-8", "replace").strip()[:200])))
        return
    missing = [m for m in out.stdout.decode().strip().split(",") if m]
    if missing:
        fails.append(fail("preconditions",
                          "the analysis environment (%s) is missing: %s. These are pinned "
                          "environment additions -- see _references/environment.md; never "
                          "pip-install them at run time."
                          % (py, ", ".join(missing))))


def run_checks(project, h5ad_path):
    fails = []
    paths = paths_for(project)
    cfg = {}
    if not paths["config"].is_file():
        fails.append(fail("preconditions", "no config at _config/%s.yaml" % ASSAY))
    else:
        cfg = wl.read_config(paths["config"])
        wl.check_config_common(cfg, REQUIRED_KEYS, fails)
        for key in ("qc.min_genes", "qc.min_cells", "n_hvg"):
            val = str(cfg.get(key, "")).strip()
            if val and "<REQUIRED" not in val and not val.isdigit():
                fails.append(fail("config", "%s %r is not a non-negative integer"
                                  % (key, val)))
        for key in ("qc.max_mito_pct", "cluster_resolution"):
            val = str(cfg.get(key, "")).strip()
            if val and "<REQUIRED" not in val:
                try:
                    float(val)
                except ValueError:
                    fails.append(fail("config", "%s %r is not a number" % (key, val)))

    if not h5ad_path:
        fails.append(fail("preconditions",
                          "--h5ad was not supplied; stage 02's router resolves it by artifact "
                          "type from 02.01's OUTPUTS.tsv"))
    else:
        p = Path(h5ad_path)
        if not p.is_file():
            fails.append(fail("preconditions", "no h5ad at %s" % p))
        elif p.stat().st_size == 0:
            fails.append(fail("preconditions", "%s is zero bytes" % p))

    if not paths["samplesheet"].is_file():
        fails.append(fail("preconditions",
                          "no samplesheet at 01_samplesheets/%s -- the exit gate checks the "
                          "analysis's per-sample cell counts against it"
                          % paths["samplesheet"].name))

    check_analysis_env(fails)
    wl.check_run_dir(paths["substage"], fails)
    return fails, cfg, paths


def cmd_check(args):
    project = Path(args.project)
    result = {"command": "check", "ok": False, "assay": ASSAY, "failures": []}
    if not project.is_dir():
        result["error"] = "no such project: %s" % project
        return emit(result, EXIT_USAGE)
    fails, cfg, paths = run_checks(project, args.h5ad)
    result["failures"] = fails
    result["ok"] = not fails
    preflight = paths["substage"] / "preflight"
    preflight.mkdir(parents=True, exist_ok=True)
    with ws.atomic_open(preflight / "check_result.json") as fh:
        json.dump({"ok": result["ok"], "failures": fails,
                   "wrapper": "scrna-qc-cluster"}, fh, indent=2, sort_keys=True)
    result["wrote"] = str((preflight / "check_result.json").relative_to(project))
    return emit(result, EXIT_OK if result["ok"] else EXIT_FAILURE)


def cmd_prepare(args):
    project = Path(args.project)
    result = {"command": "prepare", "ok": False, "assay": ASSAY, "failures": []}
    if not project.is_dir():
        result["error"] = "no such project: %s" % project
        return emit(result, EXIT_USAGE)
    fails, cfg, paths = run_checks(project, args.h5ad)
    if fails:
        result["failures"] = fails
        result["error"] = "checks failed; nothing written. Run `check` for the same detail."
        return emit(result, EXIT_FAILURE)

    substage = paths["substage"]
    (substage / "scripts").mkdir(parents=True, exist_ok=True)
    (substage / "logs").mkdir(exist_ok=True)

    # Absolute paths throughout: submit.sh runs the script from run/, so anything relative
    # here resolves against the wrong directory (the lesson recorded in 0029's validation).
    script = RUN_SCRNA_TEMPLATE.format(
        project=project.resolve().name, assay=ASSAY,
        h5ad=str(Path(args.h5ad).resolve()),
        out=str((substage / "run").resolve()),
        min_genes=cfg["qc.min_genes"], min_cells=cfg["qc.min_cells"],
        max_mito=cfg["qc.max_mito_pct"], n_hvg=cfg["n_hvg"],
        resolution=cfg["cluster_resolution"],
        mito_prefix=cfg.get("qc.mito_prefix", "MT-"))
    with ws.atomic_open(substage / "scripts" / "run_scrna.py") as fh:
        fh.write(script)

    body = '''# Single-cell QC and clustering, under gars-bio (scanpy, leidenalg, sklearn)
"$GARS_PY" "{substage}/scripts/run_scrna.py" '''.format(substage=str(substage.resolve()))
    wl.write_submit_sh(substage, WORKSPACE, cfg, project.resolve().name,
                       "%s-qc" % ASSAY, body)
    wl.write_reproducibility(substage, "scrna-qc-cluster", WORKSPACE,
                             {"h5ad": Path(args.h5ad), "config": paths["config"]},
                             [("h5ad", str(args.h5ad)),
                              ("min_genes", cfg["qc.min_genes"]),
                              ("min_cells", cfg["qc.min_cells"]),
                              ("max_mito_pct", cfg["qc.max_mito_pct"]),
                              ("n_hvg", cfg["n_hvg"]),
                              ("cluster_resolution", cfg["cluster_resolution"])])

    result.update({"ok": True,
                   "wrote": ["scripts/run_scrna.py", "submit.sh",
                             "reproducibility/manifest.json", "reproducibility/commands.sh"],
                   "submit": str((substage / "submit.sh").resolve())})
    return emit(result, EXIT_OK)


def cmd_collect(args):
    project = Path(args.project)
    result = {"command": "collect", "ok": False, "assay": ASSAY, "failures": []}
    if not project.is_dir():
        result["error"] = "no such project: %s" % project
        return emit(result, EXIT_USAGE)
    paths = paths_for(project)
    substage = paths["substage"]
    if not (substage / "run" / ".gars_run_complete").is_file():
        result["error"] = ("run/.gars_run_complete is absent: the analysis has not finished "
                           "(or crashed before the marker). collect gates on completion, it "
                           "does not wait for it.")
        return emit(result, EXIT_REFUSED)

    run = substage / "run"
    fails = []

    # --- the markers table: the 0010 defect class, checked as content ------------------------
    markers = run / "tables" / "cluster_markers.csv"
    if not markers.is_file() or markers.stat().st_size == 0:
        fails.append(fail("table", "missing or empty %s" % markers))
        rows = []
    else:
        with markers.open() as fh:
            rows = list(csv.reader(fh))
        if not rows or rows[0][0] != "gene":
            fails.append(fail("table",
                              "first column is %r, not 'gene' -- the identifier was dropped "
                              "or renamed (decision 0010)"
                              % (rows[0][0] if rows else "missing")))
        elif any(not r[0].strip() for r in rows[1:]):
            fails.append(fail("table",
                              "empty gene identifier(s) in cluster_markers.csv -- a complete, "
                              "plausible table of anonymous genes is exactly the silent "
                              "failure this gate exists for"))
        result["marker_rows"] = max(0, len(rows) - 1)

    # --- the summary, checked AGAINST the samplesheet ----------------------------------------
    # The analysis reports its own cell counts; a self-reported number trusted on its own
    # gates nothing. The samplesheet is the independent source.
    summary_path = run / "summary.json"
    summary = None
    if not summary_path.is_file():
        fails.append(fail("summary", "missing %s -- the analysis writes it last, so its "
                                     "absence means the run did not finish cleanly"
                          % summary_path))
    else:
        try:
            summary = json.loads(summary_path.read_text(encoding="utf-8"))
        except ValueError as exc:
            fails.append(fail("summary", "summary.json is not valid JSON: %s" % exc))

    if summary is not None:
        if int(summary.get("n_cells_out", 0)) <= 0:
            fails.append(fail("summary",
                              "no cells survived QC. That is a result to report, not a "
                              "threshold to lower."))
        if int(summary.get("n_clusters", 0)) <= 0:
            fails.append(fail("summary", "no clusters were found"))

        after = summary.get("cells_after_qc") or {}
        if paths["samplesheet"].is_file():
            expected = wl.samplesheet_samples(paths["samplesheet"])
            # A combined matrix carrying no sample label is analysed as one sample and says
            # so; that is honest and is not a per-sample check we can make.
            if list(after.keys()) != ["all"]:
                lost, matched = [], set()
                for s in expected:
                    # nf-core/scrnaseq labels the combined matrix's cells with the sample id
                    # PLUS its input type -- `Sample_X_filtered`, not `Sample_X` (verified on
                    # a real run). An exact match would have called every sample lost on a
                    # perfectly good result, so a label counts for a sample when it is the id
                    # or the id followed by an underscore-qualifier.
                    keys = [k for k in after
                            if k == s or k.startswith(s + "_")]
                    matched.update(keys)
                    if not keys or all(int(after[k]) <= 0 for k in keys):
                        lost.append(s)
                if lost:
                    fails.append(fail("summary",
                                      "sample(s) with no cells after QC: %s. A sample that "
                                      "vanishes here disappears from every downstream result "
                                      "and nothing else would flag it."
                                      % ", ".join(lost)))
                unknown = sorted(set(after) - matched)
                if unknown:
                    fails.append(fail("summary",
                                      "summary.json reports label(s) that match no samplesheet "
                                      "sample: %s" % ", ".join(unknown)))
            result["cells_after_qc"] = after
            result["n_clusters"] = summary.get("n_clusters")

    processed = run / "data" / "processed.h5ad"
    if not processed.is_file() or processed.stat().st_size == 0:
        fails.append(fail("h5ad", "missing or empty %s" % processed))

    for fig in ("umap_clusters.png", "violin_qc.png"):
        p = run / "figures" / fig
        if not p.is_file() or p.stat().st_size == 0:
            fails.append(fail("figure", "missing or empty %s" % p))

    report = run / "report.md"
    if not report.is_file() or report.stat().st_size == 0:
        fails.append(fail("report", "missing or empty %s" % report))

    if fails:
        result["failures"] = fails
        return emit(result, EXIT_FAILURE)

    outputs = [("h5ad", "native", "run/data/processed.h5ad"),
               ("table", "native", "run/tables/cluster_markers.csv"),
               ("figure", "native", "run/figures/umap_clusters.png"),
               ("report", "native", "run/report.md")]
    with ws.atomic_open(substage / "OUTPUTS.tsv") as fh:
        fh.write("# type\trole\tpath\n")
        for typ, role, path in outputs:
            fh.write("%s\t%s\t%s\n" % (typ, role, path))

    now = datetime.datetime.now().strftime("%Y-%m-%dT%H:%M:%S")
    with ws.atomic_open(substage / "STATUS") as fh:
        fh.write("COMPLETE %s\n" % now)

    version = ws.template_version(WORKSPACE)
    model = args.model or "unknown"
    thresholds = (summary or {}).get("thresholds", {})
    entry = "\n".join([
        "## <ISO-8601 date> — 02_bioinformatics/%s/%s — QC and clustering complete"
        % (ASSAY, SUBSTAGE),
        "",
        "Template version: %s" % version,
        "Model: %s" % model,
        "Method: scanpy (QC -> normalise -> HVG -> PCA -> neighbours -> Leiden -> Wilcoxon "
        "markers) via the gars scrna-qc-cluster wrapper",
        "Matrix supplied by: %s" % (args.h5ad_from or "unknown"),
        "Cells: %s in, %s after QC" % ((summary or {}).get("n_cells_in", "?"),
                                       (summary or {}).get("n_cells_out", "?")),
        "Clusters: %s (resolution %s)" % ((summary or {}).get("n_clusters", "?"),
                                          thresholds.get("resolution", "?")),
        "Thresholds: min_genes=%s, min_cells=%s, max_mito_pct=%s"
        % (thresholds.get("min_genes", "?"), thresholds.get("min_cells", "?"),
           thresholds.get("max_mito_pct", "?")),
        "Outputs: " + ", ".join("`%s`" % t for t, _, _ in outputs),
    ])
    result.update({"ok": True,
                   "outputs": [{"type": t, "role": r, "path": p} for t, r, p in outputs],
                   "template_version": version, "model": model, "history_entry": entry})
    return emit(result, EXIT_OK)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    sub = ap.add_subparsers(dest="cmd")
    for name in ("check", "prepare", "collect"):
        p = sub.add_parser(name)
        p.add_argument("--project", required=True)
        if name in ("check", "prepare"):
            p.add_argument("--h5ad", default=None,
                           help="path to the h5ad, resolved by artifact type by stage 02")
        if name == "collect":
            p.add_argument("--model", default="unknown",
                           help="the exact model id of the agent executing this sub-stage "
                                "(decision 0024)")
            p.add_argument("--h5ad-from", default=None,
                           help="the sub-stage that supplied the matrix, for HISTORY.md")
    args = ap.parse_args(argv)
    if not args.cmd:
        ap.print_help(sys.stderr)
        return EXIT_USAGE
    return {"check": cmd_check, "prepare": cmd_prepare, "collect": cmd_collect}[args.cmd](args)


if __name__ == "__main__":
    sys.exit(main())
