#!/usr/bin/env python3
"""The workspace's batch executor, as a setting rather than a spelling (decision 0039).

GARS submits real work to a managed scheduler and never runs it in the current process
(decision 0027). That ruling is scheduler-agnostic; only its spelling was Slurm-coupled --
`sbatch` lived in generated bytes and in contract prose, so a site without Slurm could not
run GARS at all.

This module is the one door. It reads `_config/executor.yaml` from the project and answers
three questions:

    header(...)          the directives block a generated submit.sh opens with
    submit(script)       the argv that hands that script to the scheduler -> a job id
    status(job_id)       the argv that asks after it -> PENDING | RUNNING | COMPLETED | FAILED

No descriptor file, or `name: slurm`, means the built-in Slurm descriptor, whose bytes are
identical to what this system generated before the seam existed (pinned by a golden-bytes
test). A cluster that upgrades GARS notices nothing.

The built-in `local` backend runs the generated script under `nohup`-style detachment and
reports the PID as the job id. It exists so the deterministic core can exercise a real
submit -> status -> completion walk with no cluster at all; it is POSIX-only, like every
other assumption this system already makes, and it is NOT a venue for analyses -- stage 03's
venue gate is unchanged.

Runs on stock python 3.6.8, stdlib only, like every `_system/` helper.
"""

import argparse
import json
import os
import re
import subprocess
import sys
from pathlib import Path

EXIT_OK, EXIT_FAILURE, EXIT_REFUSED, EXIT_USAGE = 0, 1, 2, 3

#: The closed state vocabulary every backend maps onto. A caller polls until it sees a
#: terminal state; nothing else is a legal answer.
STATES = ("PENDING", "RUNNING", "COMPLETED", "FAILED")

#: The placeholders a `directives` line may name. Anything else is a descriptor error, said
#: by name rather than raised as a KeyError from inside a format string.
HEADER_FIELDS = ("project", "assay", "substage", "partition", "time", "cpus", "mem")

DESCRIPTOR_NAME = "executor.yaml"

#: Where the `local` backend keeps what it needs to answer `status` for a PID it started.
LOCAL_JOBS_DIR = ".gars_local_jobs"

SLURM = {
    "name": "slurm",
    "directives": [
        "#SBATCH --job-name={project}-{assay}",
        "#SBATCH --partition={partition}",
        "#SBATCH --time={time}",
        "#SBATCH --cpus-per-task={cpus}",
        "#SBATCH --mem={mem}",
        "#SBATCH --output={substage}/logs/slurm-%j.out",
        "#SBATCH --error={substage}/logs/slurm-%j.err",
    ],
    "submit_argv": ["sbatch", "{script}"],
    "job_id_regex": r"Submitted batch job (\d+)",
    "status_argv": ["sacct", "-j", "{job_id}", "--format=State", "--noheader"],
    "status_map": {
        "PENDING": "PENDING", "CONFIGURING": "PENDING", "REQUEUED": "PENDING",
        "SUSPENDED": "PENDING", "PREEMPTED": "PENDING",
        "RUNNING": "RUNNING", "COMPLETING": "RUNNING", "RESIZING": "RUNNING",
        "COMPLETED": "COMPLETED",
        "FAILED": "FAILED", "CANCELLED": "FAILED", "TIMEOUT": "FAILED",
        "NODE_FAIL": "FAILED", "OUT_OF_MEMORY": "FAILED", "BOOT_FAIL": "FAILED",
        "DEADLINE": "FAILED", "REVOKED": "FAILED",
    },
    "nextflow_config": "nextflow.slurm.config",
    "submit_note": "Slurm snapshots this script at submission: editing it never affects a "
                   "queued job.",
}

LOCAL = {
    "name": "local",
    "directives": [
        "# Executor: local. No scheduler directives -- this script is run directly, detached.",
        "# compute.* stays in the record: partition={partition} time={time} "
        "cpus={cpus} mem={mem}",
    ],
    "submit_argv": [],          # the local backend submits in-process, not through an argv
    "job_id_regex": "",
    "status_argv": [],
    "status_map": {},
    "nextflow_config": "",
    "submit_note": "This script is run directly on this machine; editing it mid-run is a "
                   "race you will lose.",
}

BUILTINS = {"slurm": SLURM, "local": LOCAL}


# --- the descriptor ----------------------------------------------------------------------------


def _strip_value(raw):
    """A scalar: quoted span taken whole, otherwise up to an inline ` #` comment.

    Quoted first, deliberately: a Slurm directive line IS a comment (`#SBATCH ...`), so a
    naive comment strip would eat the descriptor's most important content.
    """
    raw = raw.strip()
    if raw[:1] in ('"', "'"):
        quote = raw[0]
        end = raw.find(quote, 1)
        if end != -1:
            return raw[1:end]
        return raw[1:]
    return re.split(r"\s+#", raw, maxsplit=1)[0].strip()


def parse_descriptor(text):
    """The narrow parser for a template we own -- scalars, one-level lists, one-level maps.

    The same trade `wrapperlib.read_config` makes (decision 0011): stdlib-only means no YAML
    library, and the template's shape is fixed and documented in the template itself.
    """
    values = {}
    section = None
    for raw in text.splitlines():
        if not raw.strip() or raw.lstrip().startswith("#"):
            continue
        m = re.match(r"^([A-Za-z_][A-Za-z0-9_]*):\s*(.*)$", raw)
        if m:
            key, rest = m.group(1), m.group(2)
            if rest.strip():
                values[key] = _strip_value(rest)
                section = None
            else:
                section = key
                values[key] = None      # shape decided by the first child line
            continue
        m = re.match(r"^\s+-\s+(.*)$", raw)
        if m and section:
            if not isinstance(values.get(section), list):
                values[section] = []
            values[section].append(_strip_value(m.group(1)))
            continue
        m = re.match(r"^\s+([A-Za-z_][A-Za-z0-9_]*):\s*(.*)$", raw)
        if m and section:
            if not isinstance(values.get(section), dict):
                values[section] = {}
            values[section][m.group(1)] = _strip_value(m.group(2))
            continue
    return values


def descriptor_path(config_root):
    return Path(config_root) / "_config" / DESCRIPTOR_NAME


def load(config_root):
    """The descriptor for a project. Absent file -> the built-in Slurm descriptor.

    `config_root` is the directory that owns `_config/` -- the project, in GARS's layout.
    """
    path = descriptor_path(config_root)
    if not path.is_file():
        return dict(SLURM)
    parsed = parse_descriptor(path.read_text(encoding="utf-8"))
    name = parsed.get("name") or "slurm"
    base = dict(BUILTINS.get(name, {"name": name}))
    for key, value in parsed.items():
        if value is not None:
            base[key] = value
    base.setdefault("name", name)
    return base


def validate(descriptor):
    """Problems with a descriptor, in member words. Empty list means usable."""
    problems = []
    name = descriptor.get("name")
    if not name:
        problems.append("the descriptor has no `name:` line; name the backend "
                        "(slurm, local, or your own)")
    directives = descriptor.get("directives")
    if directives is not None and not isinstance(directives, list):
        problems.append("`directives:` must be a list of `- \"...\"` lines")
    elif isinstance(directives, list):
        for line in directives:
            for field in re.findall(r"\{([A-Za-z_]+)\}", line):
                if field not in HEADER_FIELDS:
                    problems.append("directive line names {%s}, which this system does not "
                                    "supply; available: %s"
                                    % (field, ", ".join("{%s}" % f for f in HEADER_FIELDS)))
    if name not in BUILTINS:
        submit_argv = descriptor.get("submit_argv")
        if not isinstance(submit_argv, list) or not submit_argv:
            problems.append("`submit_argv:` must be a non-empty list; it runs the GENERATED "
                            "script and nothing else")
        elif not any("{script}" in a for a in submit_argv):
            problems.append("`submit_argv:` never names {script}; the generated submit.sh is "
                            "the only thing a descriptor may submit")
        status_argv = descriptor.get("status_argv")
        if not isinstance(status_argv, list) or not status_argv:
            problems.append("`status_argv:` must be a non-empty list naming {job_id}")
        elif not any("{job_id}" in a for a in status_argv):
            problems.append("`status_argv:` never names {job_id}")
        if not descriptor.get("job_id_regex"):
            problems.append("`job_id_regex:` is required: it is how the submit output "
                            "becomes a job id")
        status_map = descriptor.get("status_map")
        if not isinstance(status_map, dict) or not status_map:
            problems.append("`status_map:` must map this backend's states onto %s"
                            % "|".join(STATES))
        else:
            unknown = sorted({v for v in status_map.values() if v not in STATES})
            if unknown:
                problems.append("`status_map:` maps onto %s, which are not in the closed "
                                "vocabulary %s" % (", ".join(unknown), "|".join(STATES)))
    return problems


# --- the three doors ---------------------------------------------------------------------------


def _fill(text, fields):
    """Substitute the KNOWN {tokens} and leave every other brace alone.

    Deliberately not str.format: a descriptor element may legitimately contain literal
    braces -- the awsbatch submit argv carries a JSON --container-overrides payload, and
    format() reads {"command": ...} as a placeholder named \'"command"\' and crashes. The
    descriptor is data, not a template language; only the documented tokens are tokens.
    """
    for key, value in fields.items():
        text = text.replace("{%s}" % key, str(value))
    return text


def header_lines(config_root, cfg, project, assay, substage, descriptor=None):
    """The directives block, rendered. Returns a list of lines with no trailing newlines."""
    descriptor = descriptor if descriptor is not None else load(config_root)
    fields = {
        "project": project,
        "assay": assay,
        "substage": str(Path(substage).resolve()),
        "partition": cfg.get("compute.partition", "{partition}"),
        "time": cfg.get("compute.time", "{time}"),
        "cpus": cfg.get("compute.cpus", "{cpus}"),
        "mem": cfg.get("compute.mem", "{mem}"),
    }
    return [_fill(line, fields) for line in descriptor.get("directives") or []]


DEFAULT_SUBMIT_NOTE = ("The scheduler snapshots this script at submission: editing it never "
                       "affects a queued job.")


def submit_note(descriptor):
    """The one line the generated submit.sh says about editing itself, per backend."""
    return descriptor.get("submit_note") or DEFAULT_SUBMIT_NOTE


def config_root_for(path):
    """The nearest ancestor that owns `_config/` -- a sub-stage or analysis dir's project.

    Walked rather than counted: stage 02 sub-stages sit three levels down and stage 03
    analyses two, and a seam that hard-codes either depth breaks the other.
    """
    here = Path(path).resolve()
    for candidate in [here] + list(here.parents):
        if (candidate / "_config").is_dir():
            return candidate
    return here


def submit_argv(descriptor, script):
    return [_fill(a, {"script": script}) for a in descriptor.get("submit_argv") or []]


def status_argv(descriptor, job_id):
    return [_fill(a, {"job_id": job_id}) for a in descriptor.get("status_argv") or []]


def submit_command(config_root, script, descriptor=None):
    """The literal command line `reproducibility/commands.sh` records for this workspace."""
    descriptor = descriptor if descriptor is not None else load(config_root)
    if descriptor.get("name") == "local":
        return "python3 %s/_system/executorlib.py submit --workspace %s %s" % (
            "$WS", str(config_root), str(script))
    argv = submit_argv(descriptor, script)
    return " ".join(argv) if argv else str(script)


def _local_jobs_dir(config_root):
    return Path(config_root) / LOCAL_JOBS_DIR


#: The one-liner the `local` backend detaches. The outer shell backgrounds a subshell and
#: prints its PID, then exits -- so nothing is left for this process to wait on (no orphaned
#: Popen handle, no ResourceWarning) and the job outlives the caller, which is the point.
#: The GROUP's own descriptors go to /dev/null, not just each command's: a backgrounded job
#: inherits the caller's stdout pipe, and a pipe that stays open is a submit that blocks
#: until the job finishes -- which is exactly the thing a scheduler must never do.
LOCAL_RUNNER = ('{ bash "$1" >> "$2" 2>&1; echo $? > "$3"; } '
                '</dev/null >/dev/null 2>&1 &\necho $!\n')


def _local_submit(config_root, script):
    """Start the generated script detached; the PID is the job id.

    POSIX-only by construction, which is the posture GARS already has. The exit code lands in
    a sidecar beside the script so `status` can tell COMPLETED from FAILED once the process
    is gone -- a PID alone cannot say how a job ended.
    """
    script = Path(script).resolve()
    jobs = _local_jobs_dir(config_root)
    jobs.mkdir(parents=True, exist_ok=True)
    log = script.parent / (script.name + ".local.log")
    exit_file = script.parent / (script.name + ".local.exit")
    if exit_file.is_file():
        exit_file.unlink()          # a re-submit must never read the previous run's verdict
    proc = subprocess.run(
        ["bash", "-c", LOCAL_RUNNER, "gars-local", str(script), str(log), str(exit_file)],
        stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    job_id = (proc.stdout or b"").decode("utf-8", "replace").strip()
    if not job_id.isdigit():
        return None
    with open(str(jobs / ("%s.json" % job_id)), "w") as fh:
        json.dump({"script": str(script), "log": str(log), "exit_file": str(exit_file)},
                  fh, indent=2, sort_keys=True)
    return job_id


def _local_status(config_root, job_id):
    record = _local_jobs_dir(config_root) / ("%s.json" % job_id)
    if not record.is_file():
        return "FAILED"             # nothing here started that job; say so, never guess
    exit_file = Path(json.loads(record.read_text(encoding="utf-8"))["exit_file"])
    if exit_file.is_file():
        return "COMPLETED" if exit_file.read_text(encoding="utf-8").strip() == "0" else "FAILED"
    try:
        os.kill(int(job_id), 0)
        return "RUNNING"
    except (OSError, ValueError):
        pass
    return "FAILED"


def submit(config_root, script, descriptor=None):
    """Hand the generated script to the scheduler. Returns (job_id, detail-or-None)."""
    descriptor = descriptor if descriptor is not None else load(config_root)
    if descriptor.get("name") == "local":
        job_id = _local_submit(config_root, script)
        return (job_id, None) if job_id else (None, "the local backend printed no PID")
    argv = submit_argv(descriptor, script)
    if not argv:
        return None, "the descriptor names no submit_argv"
    try:
        proc = subprocess.run(argv, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    except OSError as exc:
        return None, "cannot run %s: %s" % (argv[0], exc)
    out = (proc.stdout or b"").decode("utf-8", "replace")
    err = (proc.stderr or b"").decode("utf-8", "replace")
    if proc.returncode != 0:
        return None, "%s exited %d: %s" % (argv[0], proc.returncode, (err or out).strip())
    m = re.search(descriptor.get("job_id_regex") or r"(\d+)", out)
    if not m:
        return None, "no job id in the submit output: %r" % out.strip()
    return m.group(1), None


def status(config_root, job_id, descriptor=None):
    """Ask after a job. Returns (state, detail-or-None); state is one of STATES."""
    descriptor = descriptor if descriptor is not None else load(config_root)
    if descriptor.get("name") == "local":
        return _local_status(config_root, job_id), None
    argv = status_argv(descriptor, job_id)
    if not argv:
        return None, "the descriptor names no status_argv"
    try:
        proc = subprocess.run(argv, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    except OSError as exc:
        return None, "cannot run %s: %s" % (argv[0], exc)
    out = (proc.stdout or b"").decode("utf-8", "replace")
    if proc.returncode != 0:
        return None, "%s exited %d" % (argv[0], proc.returncode)
    raw = ""
    for line in out.splitlines():
        if line.strip():
            raw = line.strip()
            break
    # `CANCELLED by 1234` and `COMPLETED+` are the shapes sacct actually prints.
    token = raw.split()[0].rstrip("+").upper() if raw else ""
    mapped = (descriptor.get("status_map") or {}).get(token)
    if not mapped:
        return None, "unmapped backend state %r -- add it to status_map" % (token or raw)
    return mapped, None


# --- CLI ---------------------------------------------------------------------------------------


def emit(result, code):
    json.dump(result, sys.stdout, indent=2, sort_keys=True)
    sys.stdout.write("\n")
    return code


def main(argv=None):
    # `--workspace` is accepted on either side of the subcommand: the contracts write it
    # after (`... submit --workspace <project> <script>`), a shell habit writes it before.
    common = argparse.ArgumentParser(add_help=False)
    common.add_argument("--workspace", default=argparse.SUPPRESS,
                        help="the project directory that owns _config/")
    parser = argparse.ArgumentParser(description="The workspace's batch executor (0039).",
                                     parents=[common])
    parser.set_defaults(workspace=".")
    sub = parser.add_subparsers(dest="command")

    p_header = sub.add_parser("header", parents=[common],
                              help="print the generated submit.sh directives block")
    p_header.add_argument("--project", default="{project}")
    p_header.add_argument("--assay", default="{assay}")
    p_header.add_argument("--substage", default=".")
    for key in ("partition", "time", "cpus", "mem"):
        p_header.add_argument("--" + key, default=None)

    p_submit = sub.add_parser("submit", parents=[common],
                              help="submit a GENERATED submit.sh")
    p_submit.add_argument("script")

    p_status = sub.add_parser("status", parents=[common],
                              help="the state of a submitted job")
    p_status.add_argument("job_id")

    sub.add_parser("describe", parents=[common],
                   help="the resolved descriptor and any problems with it")

    args = parser.parse_args(argv)
    if not args.command:
        parser.print_help()
        return EXIT_USAGE

    root = Path(args.workspace)
    descriptor = load(root)
    problems = validate(descriptor)
    result = {"command": args.command, "executor": descriptor.get("name"),
              "descriptor": str(descriptor_path(root)),
              "descriptor_present": descriptor_path(root).is_file()}

    if args.command == "describe":
        result["resolved"] = descriptor
        result["problems"] = problems
        result["ok"] = not problems
        return emit(result, EXIT_OK if not problems else EXIT_REFUSED)

    if problems:
        result["problems"] = problems
        return emit(result, EXIT_REFUSED)

    if args.command == "header":
        cfg = {}
        for key in ("partition", "time", "cpus", "mem"):
            value = getattr(args, key)
            if value:
                cfg["compute." + key] = value
        result["header"] = header_lines(root, cfg, args.project, args.assay, args.substage,
                                        descriptor=descriptor)
        return emit(result, EXIT_OK)

    if args.command == "submit":
        job_id, detail = submit(root, args.script, descriptor=descriptor)
        if job_id is None:
            result["error"] = detail
            return emit(result, EXIT_FAILURE)
        result["job_id"] = job_id
        result["ok"] = True
        return emit(result, EXIT_OK)

    if args.command == "status":
        state, detail = status(root, args.job_id, descriptor=descriptor)
        if state is None:
            result["error"] = detail
            return emit(result, EXIT_FAILURE)
        result["job_id"] = args.job_id
        result["state"] = state
        result["terminal"] = state in ("COMPLETED", "FAILED")
        return emit(result, EXIT_OK)

    return EXIT_USAGE


if __name__ == "__main__":
    sys.exit(main())
