#!/usr/bin/env python3
"""The workspace's batch executor, as a setting rather than a spelling (decision 0039).

GARS submits real work to a managed scheduler and never runs it in the current process
(decision 0027). That ruling is scheduler-agnostic; only its spelling was Slurm-coupled --
`sbatch` lived in generated bytes and in contract prose, so a site without Slurm could not
run GARS at all.

This module is the one door. It reads `_config/executor.yaml` from the project and answers
three questions:

    header(...)          the directives block a generated submit.sh opens with
    submit(script)       the argv that hands that script to the scheduler -> a job id
    status(job_id)       the argv that asks after it -> PENDING | RUNNING | COMPLETED | FAILED

No descriptor file, or `name: slurm`, means the built-in Slurm descriptor, whose bytes are
identical to what this system generated before the seam existed. A cluster that upgrades GARS notices nothing.

The built-in `local` backend runs the generated script under `nohup`-style detachment and
reports the PID as the job id. It exists so the deterministic core can exercise a real
submit -> status -> completion walk with no cluster at all; it is POSIX-only, like every
other assumption this system already makes. Stage 03 also uses it for an explicitly approved
`Runs: login-node (user-requested)` plan (decision 0069).

Runs on stock python 3.6.8, stdlib only, like every `_system/` helper.
"""

import argparse
import datetime
import hashlib
import signal
import shlex
import uuid
import time
import fcntl
import json
import os
import re
import subprocess
import sys
from tools.execution import shell_value, config_holds
from pathlib import Path

EXIT_OK, EXIT_FAILURE, EXIT_REFUSED, EXIT_USAGE = 0, 1, 2, 3

#: The closed state vocabulary every backend maps onto. A caller polls until it sees a
#: terminal state; nothing else is a legal answer.
STATES = ("PENDING", "RUNNING", "COMPLETED", "FAILED", "CANCELLED",
          "FAILED:TIMEOUT", "FAILED:OUT_OF_MEMORY", "FAILED:NODE_FAIL")

#: The placeholders a `directives` line may name. Anything else is a descriptor error, said
#: by name rather than raised as a KeyError from inside a format string.
HEADER_FIELDS = ("project", "assay", "substage", "partition", "time", "cpus", "mem")

DESCRIPTOR_NAME = "executor.yaml"

#: Where the `local` backend keeps what it needs to answer `status` for a PID it started.
LOCAL_JOBS_DIR = ".gars_local_jobs"

SLURM = {
    "name": "slurm",
    "directives": [
        "#SBATCH --job-name={project}-{assay}",
        "#SBATCH --partition={partition}",
        "#SBATCH --time={time}",
        "#SBATCH --cpus-per-task={cpus}",
        "#SBATCH --mem={mem}",
        "#SBATCH --output={substage}/logs/slurm-%j.out",
        "#SBATCH --error={substage}/logs/slurm-%j.err",
    ],
    "submit_argv": ["sbatch", "{script}"],
    "job_id_regex": r"Submitted batch job (\d+)",
    "cancel_argv": ["scancel", "{job_id}"],
    "start_argv": ["sacct", "-j", "{job_id}", "--format=Start", "--noheader", "--parsable2"],
    "status_argv": ["sacct", "-j", "{job_id}", "--format=State,ExitCode", "--noheader", "--parsable2"],
    "status_map": {
        "PENDING": "PENDING", "CONFIGURING": "PENDING", "REQUEUED": "PENDING",
        "SUSPENDED": "PENDING", "PREEMPTED": "PENDING",
        "RUNNING": "RUNNING", "COMPLETING": "RUNNING", "RESIZING": "RUNNING",
        "COMPLETED": "COMPLETED",
        "FAILED": "FAILED", "CANCELLED": "CANCELLED", "TIMEOUT": "FAILED:TIMEOUT",
        "NODE_FAIL": "FAILED:NODE_FAIL", "OUT_OF_MEMORY": "FAILED:OUT_OF_MEMORY", "BOOT_FAIL": "FAILED",
        "DEADLINE": "FAILED", "REVOKED": "FAILED",
    },
    "nextflow_config": "nextflow.slurm.config",
    #: The -profile the generated submit body passes to nextflow. A container runtime is a
    #: property of the venue, not of the science: this cluster runs apptainer; AWS Batch
    #: supplies each process's container itself and wants no profile at all (empty = omit).
    "nextflow_profile": "apptainer",
    "submit_note": "Slurm snapshots this script at submission: editing it never affects a "
                   "queued job.",
}

LOCAL = {
    "name": "local",
    "directives": [
        "# Executor: local. No scheduler directives -- this script is run directly, detached.",
        "# compute.* stays in the record: partition={partition} time={time} "
        "cpus={cpus} mem={mem}",
    ],
    "submit_argv": [],          # the local backend submits in-process, not through an argv
    "job_id_regex": "",
    "status_argv": [],
    "cancel_argv": [],
    "start_argv": [],
    "status_map": {},
    "nextflow_config": "",
    "nextflow_profile": "",
    "submit_note": "This script is run directly on this machine; editing it mid-run is a "
                   "race you will lose.",
}

BUILTINS = {"slurm": SLURM, "local": LOCAL}


# --- the descriptor ----------------------------------------------------------------------------


def _strip_value(raw):
    """A scalar: quoted span taken whole, otherwise up to an inline ` #` comment.

    Quoted first, deliberately: a Slurm directive line IS a comment (`#SBATCH ...`), so a
    naive comment strip would eat the descriptor's most important content.
    """
    raw = raw.strip()
    if raw[:1] in ('"', "'"):
        quote = raw[0]
        end = raw.find(quote, 1)
        if end != -1:
            return raw[1:end]
        return raw[1:]
    return re.split(r"\s+#", raw, maxsplit=1)[0].strip()


def parse_descriptor(text):
    """The narrow parser for a template we own -- scalars, one-level lists, one-level maps.

    The same trade `wrapperlib.read_config` makes (decision 0011): stdlib-only means no YAML
    library, and the template's shape is fixed and documented in the template itself.
    """
    values = {}
    section = None
    for raw in text.splitlines():
        if not raw.strip() or raw.lstrip().startswith("#"):
            continue
        m = re.match(r"^([A-Za-z_][A-Za-z0-9_]*):\s*(.*)$", raw)
        if m:
            key, rest = m.group(1), m.group(2)
            if rest.strip():
                values[key] = _strip_value(rest)
                section = None
            else:
                section = key
                values[key] = None      # shape decided by the first child line
            continue
        m = re.match(r"^\s+-\s+(.*)$", raw)
        if m and section:
            if not isinstance(values.get(section), list):
                values[section] = []
            values[section].append(_strip_value(m.group(1)))
            continue
        m = re.match(r"^\s+([A-Za-z_][A-Za-z0-9_]*):\s*(.*)$", raw)
        if m and section:
            if not isinstance(values.get(section), dict):
                values[section] = {}
            values[section][m.group(1)] = _strip_value(m.group(2))
            continue
    return values


def descriptor_path(config_root):
    return Path(config_root) / "_config" / DESCRIPTOR_NAME


def load(config_root):
    """The descriptor for a project. Absent file -> the built-in Slurm descriptor.

    `config_root` is the directory that owns `_config/` -- the project, in GARS's layout.
    """
    path = descriptor_path(config_root)
    if not path.is_file():
        return dict(SLURM)
    parsed = parse_descriptor(path.read_text(encoding="utf-8"))
    name = parsed.get("name") or "slurm"
    base = dict(BUILTINS.get(name, {"name": name}))
    for key, value in parsed.items():
        if value is not None:
            base[key] = value
    base.setdefault("name", name)
    return base


def validate(descriptor):
    """Problems with a descriptor, in member words. Empty list means usable."""
    problems = []
    name = descriptor.get("name")
    if name not in BUILTINS:
        problems.append('R-075: backend must be the enum slurm|local')
    else:
        for key in ('submit_argv', 'status_argv', 'cancel_argv', 'start_argv', 'job_id_regex', 'status_map', 'submit_note'):
            if key in descriptor and descriptor[key] != BUILTINS[name].get(key):
                problems.append('R-075: %s is fixed by the backend enum' % key)
    for key in ('nextflow_config', 'nextflow_profile'):
        value = descriptor.get(key)
        if value:
            try:
                shell_value(value, key)
            except ValueError as exc:
                problems.append(str(exc))
    # Free-form directive templates would be a second executable language.
    if name in BUILTINS and descriptor.get('directives') != BUILTINS[name]['directives']:
        problems.append('R-075: directives must match the registered backend')
    if not name:
        problems.append("the descriptor has no `name:` line; name the backend "
                        "(slurm, local, or your own)")
    directives = descriptor.get("directives")
    if directives is not None and not isinstance(directives, list):
        problems.append("`directives:` must be a list of `- \"...\"` lines")
    elif isinstance(directives, list):
        for line in directives:
            for field in re.findall(r"\{([A-Za-z_]+)\}", line):
                if field not in HEADER_FIELDS:
                    problems.append("directive line names {%s}, which this system does not "
                                    "supply; available: %s"
                                    % (field, ", ".join("{%s}" % f for f in HEADER_FIELDS)))
    if name not in BUILTINS:
        submit_argv = descriptor.get("submit_argv")
        if not isinstance(submit_argv, list) or not submit_argv:
            problems.append("`submit_argv:` must be a non-empty list; it runs the GENERATED "
                            "script and nothing else")
        elif not any("{script}" in a for a in submit_argv):
            problems.append("`submit_argv:` never names {script}; the generated submit.sh is "
                            "the only thing a descriptor may submit")
        status_argv = descriptor.get("status_argv")
        if not isinstance(status_argv, list) or not status_argv:
            problems.append("`status_argv:` must be a non-empty list naming {job_id}")
        elif not any("{job_id}" in a for a in status_argv):
            problems.append("`status_argv:` never names {job_id}")
        if not descriptor.get("job_id_regex"):
            problems.append("`job_id_regex:` is required: it is how the submit output "
                            "becomes a job id")
        else:
            try:
                re.compile(descriptor["job_id_regex"])
            except re.error as exc:
                problems.append("`job_id_regex:` does not compile (%s) -- remember the "
                                "parser takes a quoted value verbatim, with no escape "
                                "processing; a regex needing a double quote must be "
                                "single-quoted" % exc)
        status_map = descriptor.get("status_map")
        if not isinstance(status_map, dict) or not status_map:
            problems.append("`status_map:` must map this backend's states onto %s"
                            % "|".join(STATES))
        else:
            unknown = sorted({v for v in status_map.values() if v not in STATES})
            if unknown:
                problems.append("`status_map:` maps onto %s, which are not in the closed "
                                "vocabulary %s" % (", ".join(unknown), "|".join(STATES)))
    return problems


# --- the three doors ---------------------------------------------------------------------------


def _fill(text, fields):
    """Substitute the KNOWN {tokens} and leave every other brace alone.

    Deliberately not str.format: a descriptor element may legitimately contain literal
    braces -- the awsbatch submit argv carries a JSON --container-overrides payload, and
    format() reads {"command": ...} as a placeholder named \'"command"\' and crashes. The
    descriptor is data, not a template language; only the documented tokens are tokens.
    """
    for key, value in fields.items():
        text = text.replace("{%s}" % key, str(value))
    return text


def header_lines(config_root, cfg, project, assay, substage, descriptor=None):
    """The directives block, rendered. Returns a list of lines with no trailing newlines."""
    descriptor = descriptor if descriptor is not None else load(config_root)
    fields = {
        "project": project,
        "assay": assay,
        "substage": str(Path(substage).resolve()),
        "partition": cfg.get("compute.partition", "{partition}"),
        "time": cfg.get("compute.time", "{time}"),
        "cpus": cfg.get("compute.cpus", "{cpus}"),
        "mem": cfg.get("compute.mem", "{mem}"),
    }
    problems = validate(descriptor)
    if problems:
        raise ValueError('; '.join(problems))
    fields = {key: (value if key in ('partition', 'time', 'cpus', 'mem')
                          and 'compute.' + key not in cfg
                          else shell_value(value, key)) for key, value in fields.items()}
    return [_fill(line, fields) for line in descriptor.get("directives") or []]


DEFAULT_SUBMIT_NOTE = ("The scheduler snapshots this script at submission: editing it never "
                       "affects a queued job.")


def submit_note(descriptor):
    """The one line the generated submit.sh says about editing itself, per backend."""
    return descriptor.get("submit_note") or DEFAULT_SUBMIT_NOTE


def config_root_for(path):
    """The nearest ancestor that owns `_config/` -- a sub-stage or analysis dir's project.

    Walked rather than counted: stage 02 sub-stages sit three levels down and stage 03
    analyses two, and a seam that hard-codes either depth breaks the other.
    """
    here = Path(path).resolve()
    for candidate in [here] + list(here.parents):
        if (candidate / "_config").is_dir():
            return candidate
    return here


# Explicit exported names; no arbitrary inherited credentials (R-096, executor half).
EXPORT_NAMES = ('PATH', 'HOME', 'USER', 'LOGNAME', 'LANG', 'LC_ALL', 'TMPDIR', 'TEMP',
                'TMP', 'GARS_ROOT', 'GARS_PIPELINES')


def execution_env():
    return {key: value for key, value in os.environ.items() if key in EXPORT_NAMES}


def submit_argv(descriptor, script):
    problems = validate(descriptor)
    if problems:
        raise ValueError('; '.join(problems))
    shell_value(script, 'script')
    argv = [_fill(a, {"script": script}) for a in BUILTINS[descriptor['name']]['submit_argv']]
    if descriptor['name'] == 'slurm':
        argv.insert(1, '--export=' + ','.join(EXPORT_NAMES))
    return argv


def status_argv(descriptor, job_id):
    return [_fill(a, {"job_id": job_id}) for a in descriptor.get("status_argv") or []]


def nextflow_config_path(config_root, descriptor=None):
    """The nextflow config file this workspace's executor pairs with, or None.

    The descriptor names it (0039); callers must never spell `nextflow.slurm.config`
    themselves -- that name is the Slurm default, not a law.
    """
    descriptor = descriptor if descriptor is not None else load(config_root)
    name = descriptor.get("nextflow_config") or ""
    return (Path(config_root) / "_config" / name) if name else None


def nextflow_profile(config_root, descriptor=None):
    """The -profile the generated submit body passes, '' meaning none."""
    descriptor = descriptor if descriptor is not None else load(config_root)
    value = descriptor.get("nextflow_profile")
    return SLURM["nextflow_profile"] if value is None else value


def submit_command(config_root, script, descriptor=None):
    """The literal command line `reproducibility/commands.sh` records for this workspace."""
    descriptor = descriptor if descriptor is not None else load(config_root)
    if descriptor.get("name") == "local":
        return "python3 %s/_system/executorlib.py submit --workspace %s %s" % (
            "$WS", str(config_root), str(script))
    argv = submit_argv(descriptor, script)
    return " ".join(argv) if argv else str(script)


def _local_jobs_dir(config_root):
    return Path(config_root) / LOCAL_JOBS_DIR


#: The one-liner the `local` backend detaches. The outer shell backgrounds a subshell and
#: prints its PID, then exits -- so nothing is left for this process to wait on (no orphaned
#: Popen handle, no ResourceWarning) and the job outlives the caller, which is the point.
#: The GROUP's own descriptors go to /dev/null, not just each command's: a backgrounded job
#: inherits the caller's stdout pipe, and a pipe that stays open is a submit that blocks
#: until the job finishes -- which is exactly the thing a scheduler must never do.
LOCAL_RUNNER = ("{ trap 'kill -TERM \"$worker\" 2>/dev/null; wait \"$worker\"; "
                "echo 143 > \"$3\"; exit 143' TERM; "
                'bash "$1" >> "$2" 2>&1 & worker=$!; wait "$worker"; echo $? > "$3"; } '
                '</dev/null >/dev/null 2>&1 &\necho $!\n')


def _local_submit(config_root, script):
    """Start the generated script detached; the PID is the job id.

    POSIX-only by construction, which is the posture GARS already has. The exit code lands in
    a sidecar beside the script so `status` can tell COMPLETED from FAILED once the process
    is gone -- a PID alone cannot say how a job ended.
    """
    script = Path(script).resolve()
    jobs = _local_jobs_dir(config_root)
    jobs.mkdir(parents=True, exist_ok=True)
    log = script.parent / (script.name + ".local.log")
    exit_file = script.parent / (script.name + ".local.exit")
    if exit_file.is_file():
        exit_file.unlink()          # a re-submit must never read the previous run's verdict
    try:
        proc = subprocess.run(
            ["bash", "-c", LOCAL_RUNNER, "gars-local", str(script), str(log), str(exit_file)],
            stdout=subprocess.PIPE, stderr=subprocess.PIPE, env=execution_env())
    except OSError as exc:
        raise BackendUnavailable(str(exc))
    job_id = (proc.stdout or b"").decode("utf-8", "replace").strip()
    if not job_id.isdigit():
        return None
    with open(str(jobs / ("%s.json" % job_id)), "w") as fh:
        json.dump({"script": str(script), "log": str(log), "exit_file": str(exit_file), "started_at": time.time()},
                  fh, indent=2, sort_keys=True)
    return job_id


def _local_status(config_root, job_id):
    record = _local_jobs_dir(config_root) / ("%s.json" % job_id)
    if not record.is_file():
        return "FAILED"             # nothing here started that job; say so, never guess
    exit_file = Path(json.loads(record.read_text(encoding="utf-8"))["exit_file"])
    if exit_file.is_file():
        code = exit_file.read_text(encoding="utf-8").strip()
        return "COMPLETED" if code == "0" else ('FAILED:EXIT_' + code if code.isdigit() else 'FAILED')
    try:
        os.kill(int(job_id), 0)
        return "RUNNING"
    except (OSError, ValueError):
        pass
    return "FAILED"


class SubmissionFailure(str):
    """A definite rejection before a backend accepted a job; still a JSON string."""


class BackendUnavailable(OSError):
    """The local process could not be launched at all."""


def _submit_once(config_root, script, descriptor=None):
    """Hand the generated script to the scheduler. Returns (job_id, detail-or-None)."""
    descriptor = descriptor if descriptor is not None else load(config_root)
    problems = validate(descriptor)
    if problems:
        return None, SubmissionFailure('; '.join(problems))
    stage = Path(script).resolve().parent
    # Stage-02 locations identify the assay independently of the writable manifest.
    try:
        parts = stage.relative_to(Path(config_root).resolve()).parts
    except ValueError:
        return None, SubmissionFailure('R-073: script is outside its project')
    if len(parts) >= 3 and parts[0] == '02_bioinformatics':
        problem = config_holds(config_root, stage, parts[1])
        if problem:
            return None, SubmissionFailure(problem)
    elif len(parts) >= 2 and parts[0] == '03_custom_analysis':
        stage = Path(config_root).resolve().joinpath(*parts[:2])
        from stage03_analysis import approval_holds, approval_record_path, ws
        workspace = ws.workspace_root(__file__)
        holds, why = approval_holds(stage / 'PLAN.md',
                                    approval_record_path(stage / 'PLAN.md', workspace), workspace)
        if not holds:
            return None, SubmissionFailure('R-073: ' + why)
    else:
        return None, SubmissionFailure('R-073: submit requires a prepared stage or approved analysis')
    if descriptor.get("name") == "local":
        try:
            job_id = _local_submit(config_root, script)
        except BackendUnavailable as exc:
            return None, SubmissionFailure('cannot run local backend: %s' % exc)
        except OSError as exc:
            # Local record creation can fail after launching; preserve the reservation.
            return None, 'local submission unresolved: %s' % exc
        return (job_id, None) if job_id else (None, "the local backend printed no PID")
    argv = submit_argv(descriptor, script)
    if not argv:
        return None, SubmissionFailure("the descriptor names no submit_argv")
    try:
        proc = subprocess.run(argv, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                              env=execution_env())
    except OSError as exc:
        return None, SubmissionFailure("cannot run %s: %s" % (argv[0], exc))
    out = (proc.stdout or b"").decode("utf-8", "replace")
    err = (proc.stderr or b"").decode("utf-8", "replace")
    try:
        m = re.search(descriptor.get("job_id_regex") or r"(\d+)", out)
    except re.error as exc:
        return None, "job_id_regex does not compile: %s" % exc
    if proc.returncode != 0:
        detail = "%s exited %d: %s" % (argv[0], proc.returncode, (err or out).strip())
        # A signal or any printed job identity makes acceptance ambiguous.
        has_identity = m or re.search(descriptor.get('job_id_regex') or r'(\d+)', err)
        return None, SubmissionFailure(detail) if proc.returncode > 0 and not has_identity else detail
    if not m:
        return None, "no job id in the submit output: %r" % out.strip()
    return m.group(1), None


def _scheduler_status(config_root, job_id, descriptor=None):
    """Ask after a job. Returns (state, detail-or-None); state is one of STATES."""
    descriptor = descriptor if descriptor is not None else load(config_root)
    if descriptor.get("name") == "local":
        return _local_status(config_root, job_id), None
    argv = status_argv(descriptor, job_id)
    if not argv:
        return None, "the descriptor names no status_argv"
    try:
        proc = subprocess.run(argv, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                              env=execution_env())
    except OSError as exc:
        return None, "cannot run %s: %s" % (argv[0], exc)
    out = (proc.stdout or b"").decode("utf-8", "replace")
    if proc.returncode != 0:
        return None, "%s exited %d" % (argv[0], proc.returncode)
    raw = ""
    for line in out.splitlines():
        if line.strip():
            raw = line.strip()
            break
    # `CANCELLED by 1234` and `COMPLETED+` are the shapes sacct actually prints.
    fields = raw.split('|')
    token = fields[0].split()[0].rstrip("+").upper() if fields[0] else ""
    mapped = (descriptor.get("status_map") or {}).get(token)
    if not mapped:
        return None, "unmapped backend state %r -- add it to status_map" % (token or raw)
    if mapped == 'FAILED' and len(fields) > 1:
        exit_code = fields[1].split(':')[0]
        if exit_code.isdigit() and int(exit_code) > 0:
            mapped = 'FAILED:EXIT_' + str(int(exit_code))
    return mapped, None


def recorded_state(record):
    """Recorded scheduler state, never an agent-authored STATUS value."""
    return record['state']


def _records(config_root):
    return Path(config_root) / '.gars_submissions'


def _save_record(path, record):
    import wrapperlib as wl
    with wl.ws.atomic_open(path) as fh:
        json.dump(record, fh, indent=2, sort_keys=True)
        fh.write('\n')


def _job_record(config_root, job_id):
    for path in _records(config_root).glob('*.json'):
        record = json.loads(path.read_text(encoding='utf-8'))
        if record.get('job_id') == str(job_id):
            return path, record
    return None, None


def prepared_key(config_root, stage):
    """Recompute R-076 from current bytes, not the manifest's claimed digest."""
    import hashlib
    import wrapperlib as wl
    stage = Path(stage).resolve()
    parts = stage.relative_to(Path(config_root).resolve()).parts
    if len(parts) != 3 or parts[0] != '02_bioinformatics':
        raise ValueError('key requires a stage-02 directory')
    manifest = json.loads((stage / 'reproducibility/manifest.json').read_text(encoding='utf-8'))
    if 'inputs' in manifest:
        if Path(manifest['inputs']['config']).resolve() != (Path(config_root) / '_config' / (parts[1] + '.yaml')).resolve():
            raise ValueError('config input differs from stage assay')
        key = wl.input_key(stage, manifest)
    else:
        params = stage / 'params.yaml'
        sheet = Path(wl.read_config(params)['input'])
        if not sheet.is_absolute():
            raise ValueError('prepared samplesheet must be absolute')
        digest = hashlib.sha256()
        for source in (params, sheet, Path(config_root) / '_config' / (parts[1] + '.yaml')):
            with source.open('rb') as fh:
                for chunk in iter(lambda: fh.read(1 << 20), b''):
                    digest.update(chunk)
        key = digest.hexdigest()
    comments = [line for line in (stage / 'submit.sh').read_text(encoding='utf-8').splitlines()
                if line.startswith('# idempotency_key=')]
    if manifest.get('idempotency_key') != key or comments != ['# idempotency_key=' + key]:
        raise ValueError('prepared key differs from input bytes')
    return key


def _validate_record(config_root, path, record):
    """Validate immutable submission identity without consulting re-prepared inputs.

    The key was recomputed before reservation. Its protected record remains the job's
    identity after prepare replaces the current script/manifest with another key.
    Collection separately requires the current prepared_key via stage_record().
    """
    key = record.get('idempotency_key')
    if not isinstance(key, str) or not re.fullmatch(r'[0-9a-f]{64}', key) or path.name != key + '.json':
        raise ValueError('record key differs from its reservation')
    script = Path(record['script'])
    stage = script.parent.resolve()
    parts = stage.relative_to(Path(config_root).resolve()).parts
    if (len(parts) != 3 or parts[0] != '02_bioinformatics' or
            str(script) != str(stage / 'submit.sh') or not script.is_file()):
        raise ValueError('record script is not a generated stage script')
    return stage


def _stage_records(config_root, stage):
    records = []
    for path in _records(config_root).glob('*.json'):
        record = json.loads(path.read_text(encoding='utf-8'))
        if Path(record['script']).parent.resolve() == stage:
            _validate_record(config_root, path, record)
            records.append(record)
    return records


def _scheduler_terminal(state):
    return state in ('COMPLETED', 'CANCELLED') or state.startswith('FAILED')


def stage_record(config_root, stage):
    """Bind collection to this stage's recomputed key and recorded script identity."""
    stage = Path(stage).resolve()
    manifest_path = stage / 'reproducibility/manifest.json'
    if not manifest_path.exists():
        return None  # Legacy unrecorded collect remains outside row 12's boundary.
    manifest = json.loads(manifest_path.read_text(encoding='utf-8'))
    if 'idempotency_key' not in manifest:
        raise ValueError('prepared manifest has no idempotency key')
    key = prepared_key(config_root, stage)
    path = _records(config_root) / (key + '.json')
    if not path.is_file():
        raise ValueError('prepared key has no submission record')
    record = json.loads(path.read_text(encoding='utf-8'))
    if (record.get('idempotency_key') != key or
            record.get('script') != str(stage / 'submit.sh')):
        raise ValueError('submission record does not belong to this stage')
    return record


def classify(state, exit_code):
    """Owner's deterministic R-152 mapping; no inferred agent/science codes."""
    reason = str(state).split(':', 1)[-1]
    if reason in ('TIMEOUT', 'OUT_OF_MEMORY', 'NODE_FAIL'):
        return 'infrastructure'
    if reason.startswith('EXIT_'):
        exit_code = int(reason[5:])
    if state == 'CANCELLED' or reason == 'CANCELLED':
        return 'workflow'
    if exit_code == 104 or exit_code in range(130, 146):
        return 'transient'
    if exit_code in (126, 127):
        return 'tool'
    if exit_code == 65:
        return 'data_quality'
    return 'workflow' if exit_code or str(state).startswith('FAILED') else None


def record_failure(stage, record, state, detail):
    import wrapperlib as wl
    category = classify(state, None)
    stem = 'failure-' + str(record.get('job_id') or 'collect')
    logs = Path(stage) / 'logs'
    logs.mkdir(exist_ok=True)
    for suffix, text in (('.log', detail), ('.class', category)):
        with wl.ws.atomic_open(logs / (stem + suffix)) as fh:
            fh.write(text + '\n')
    record['failure_class'] = category
    record['failure_artifact'] = str(logs / (stem + '.class'))


def retry_refusal(root, stage, record, retries):
    """Consume recorded class evidence and the existing configured retry ceiling."""
    if record['state'] == 'CANCELLED':
        return 'R-152: retry_refused: the job was cancelled; prepare corrected inputs'
    try:
        category = Path(record['failure_artifact']).read_text().strip()
        if category != record['failure_class'] or category != classify(record['state'], None):
            raise ValueError('failure class differs from scheduler evidence')
        if category != 'transient':
            raise ValueError('only transient failures retry')
        config = Path(root) / '_config/nextflow.slurm.config'
        text = config.read_text()
        values = re.findall(r'^\s*maxRetries\s*=\s*([0-9]+)\s*(?://.*)?$', text, re.M)
        if len(values) != 1 or retries >= int(values[0]):
            raise ValueError('maxRetries exhausted or ambiguous')
        if record.get('destructive', False):
            holds, why = action_approval_holds(root, record, 'retry')
            if not holds:
                raise ValueError(why)
    except (OSError, ValueError, KeyError, TypeError) as exc:
        return 'R-152: retry_refused: %s' % exc
    return None


def _action_plan(root, record, action):
    return {'action': action, 'job_id': record['job_id'], 'backend': record['executor'],
            'project': str(Path(root).resolve()), 'script': record['script'],
            'idempotency_key': record['idempotency_key']}


def _action_paths(root, record, action):
    import stage03_analysis as analysis
    workspace = analysis.ws.workspace_root(__file__)
    plan = _action_plan(root, record, action)
    data = (json.dumps(plan, sort_keys=True, separators=(',', ':')) + '\n').encode('utf-8')
    path = analysis.approval_store(workspace) / (hashlib.sha256(data).hexdigest() + '.plan.json')
    return analysis, workspace, plan, data, path


def action_approval_holds(root, record, action):
    analysis, workspace, plan, data, path = _action_paths(root, record, action)
    approved = analysis.approval_record_path(path, workspace)
    holds, why = analysis.approval_holds(path, approved, workspace)
    if not holds:
        return holds, why
    try:
        approval = json.loads(approved.read_text())
        if path.read_bytes() != data or any(approval.get(k) != plan[k] for k in ('action', 'job_id', 'backend')):
            return False, 'R-073: action/job/backend approval mismatch'
    except (OSError, ValueError):
        return False, 'R-073: unreadable action approval'
    return True, None


def approve_action(root, job_id, action):
    """Human-only CLI, absent from the typed registry and refused by the guard."""
    path, record = _job_record(root, job_id)
    if not record:
        return False, 'R-073: job has no submission record'
    _validate_record(root, path, record)
    analysis, workspace, plan, data, plan_path = _action_paths(root, record, action)
    analysis.check_store(workspace, create=True)
    now = datetime.datetime.now(datetime.timezone.utc).replace(microsecond=0)
    approval = {'actor': analysis.LAUNCH_ACTOR,
                'timestamp': now.strftime('%Y-%m-%dT%H:%M:%SZ'),
                'expiry': (now + analysis.APPROVAL_LIFETIME).strftime('%Y-%m-%dT%H:%M:%SZ'),
                'plan_sha256': hashlib.sha256(data).hexdigest(), 'plan_path': str(plan_path),
                'action': action, 'job_id': record['job_id'], 'backend': record['executor']}
    approved = analysis.approval_record_path(plan_path, workspace)
    for target, content in ((plan_path, data), (approved, (json.dumps(approval, sort_keys=True) + '\n').encode())):
        fd = os.open(str(target), os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
        with os.fdopen(fd, 'wb') as fh:
            fh.write(content)
    return True, None


def scheduler_start(root, record, descriptor):
    if descriptor['name'] == 'local':
        path = _local_jobs_dir(root) / (record['job_id'] + '.json')
        try:
            return json.loads(path.read_text()).get('started_at')
        except (OSError, ValueError):
            return None
    argv = [_fill(a, {'job_id': record['job_id']}) for a in descriptor['start_argv']]
    try:
        proc = subprocess.run(argv, stdout=subprocess.PIPE, stderr=subprocess.PIPE, env=dict(execution_env(), TZ='UTC'))
        if proc.returncode:
            return None
        raw = proc.stdout.decode().strip().splitlines()[0].split('|')[0]
        # sacct Start is local scheduler wall time; request UTC explicitly.
        return datetime.datetime.strptime(raw, '%Y-%m-%dT%H:%M:%S').replace(tzinfo=datetime.timezone.utc).timestamp()
    except (OSError, ValueError, IndexError):
        return None


def cancel(root, job_id, descriptor=None):
    import wrapperlib as wl
    descriptor = descriptor if descriptor is not None else load(root)
    problems = validate(descriptor)
    if problems:
        return False, '; '.join(problems)
    directory = _records(root)
    if not directory.is_dir():
        return False, 'R-074: cancellation requires a recorded job'
    with open(str(directory / '.lock'), 'a') as lock:
        fcntl.flock(lock.fileno(), fcntl.LOCK_EX)
        path, record = _job_record(root, job_id)
        if not record or record.get('executor') != descriptor['name']:
            return False, 'R-074: job/backend differs from submission record'
        stage = _validate_record(root, path, record)
        if _scheduler_terminal(record['state']):
            return record['state'] == 'CANCELLED', 'job is already terminal'
        previous = wl.read_status(stage)
        if previous and previous.split(':', 1)[0] in wl.TERMINAL_STATES:
            return False, 'R-074: stage is already terminal; reconcile recorded job'
        observed = _scheduler_status(root, job_id, descriptor)
        if observed[0] is None:
            return False, 'R-077: scheduler state unknown; cancel refused: %s' % observed[1]
        if _scheduler_terminal(observed[0]):
            _status_locked(root, job_id, descriptor, observed=observed)
            saved = _job_record(root, job_id)[1]['state']
            return saved == 'CANCELLED', 'cancel refused: recorded state %s' % saved
        started = scheduler_start(root, record, descriptor)
        if started is not None:
            record['started_at'] = started
        _save_record(path, record)
        since = record.get('started_at') or record.get('submitted_at')
        if not isinstance(since, (int, float)) or not 0 <= time.time() - since <= 3600:
            holds, why = action_approval_holds(root, record, 'cancel')
            if not holds:
                return False, 'R-074: cancellation needs job/backend approval: %s' % why
        try:
            if descriptor['name'] == 'local':
                local_path = _local_jobs_dir(root) / (str(job_id) + '.json')
                local = json.loads(local_path.read_text())
                if local.get('script') != record['script']:
                    return False, 'R-074: local PID record differs from submission'
                os.kill(int(job_id), signal.SIGTERM)
            else:
                argv = [_fill(a, {'job_id': job_id}) for a in descriptor['cancel_argv']]
                proc = subprocess.run(argv, stdout=subprocess.PIPE, stderr=subprocess.PIPE, env=execution_env())
                if proc.returncode:
                    return False, 'scancel exited %d' % proc.returncode
        except (OSError, ValueError) as exc:
            return False, 'cancellation failed: %s' % exc
        record['state'] = 'CANCELLED'
        _save_record(path, record)
        wl.write_status(stage, 'CANCELLED')
        return True, None


ANALYSIS_SUBMISSIONS = '.gars_submissions.jsonl'


def analysis_directory(root, script):
    """The first two project-relative parts own even scripts in nested folders."""
    root = Path(root).resolve()
    parts = Path(script).resolve().relative_to(root).parts
    if len(parts) < 3 or parts[0] != '03_custom_analysis':
        raise ValueError('script must be inside a stage-03 analysis')
    return root.joinpath(*parts[:2])


def _analysis_entries(adir):
    path = Path(adir) / ANALYSIS_SUBMISSIONS
    if not path.is_file():
        return []
    return [json.loads(line) for line in path.read_text(encoding='utf-8').splitlines()]


def _analysis_latest(entries):
    latest = {}
    for entry in entries:
        latest[entry['script']] = entry
    return latest


def _sha256(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def _analysis_approval(adir):
    from stage03_analysis import approval_holds, approval_record_path, ws
    workspace = ws.workspace_root(__file__)
    plan = adir / 'PLAN.md'
    return approval_holds(plan, approval_record_path(plan, workspace), workspace)


def _analysis_descriptor(adir, descriptor):
    text = (adir / 'PLAN.md').read_text(encoding='utf-8')
    if re.search(r'^Runs: login-node \(user-requested\)\s*$', text, re.M):
        return LOCAL
    return descriptor


def _analysis_launcher(adir, script, descriptor):
    """Keep leading Slurm directives byte-for-byte; only this launcher owns success."""
    source = Path(script).read_bytes()
    directives = []
    for line in source.splitlines(keepends=True):
        if line.strip() and not line.lstrip().startswith(b'#'):
            break
        if line.startswith(b'#SBATCH'):
            directives.append(line)
    launcher = adir / 'run' / ('launch-' + uuid.uuid4().hex + '.sh')
    marker = shlex.quote(str(adir / 'run/.gars_run_complete'))
    body = ('cd %s || exit 1\n'
            'rm -f -- %s || exit 1\n'
            'bash %s\n'
            'code=$?\n'
            'if [ "$code" -eq 0 ]; then\n'
            '    : > %s\n'
            'else\n'
            '    rm -f -- %s\n'
            'fi\n'
            'exit "$code"\n') % (shlex.quote(str(adir)), marker,
                                      shlex.quote(str(script)), marker, marker)
    header = b'#!/bin/bash\n' + (b''.join(directives) if descriptor['name'] == 'slurm' else b'')
    if not header.endswith(b'\n'):
        header += b'\n'
    launcher.write_bytes(header + body.encode('utf-8'))
    return launcher


def _submit_analysis(root, script, descriptor):
    script = Path(script).resolve()
    adir = analysis_directory(root, script)
    holds, why = _analysis_approval(adir)
    if not holds:
        return None, 'R-073: ' + why
    descriptor = _analysis_descriptor(adir, descriptor)
    problems = validate(descriptor)
    if problems:
        return None, '; '.join(problems)
    run = adir / 'run'
    run.mkdir(exist_ok=True)
    with (run / '.submission.lock').open('a') as lock:
        fcntl.flock(lock.fileno(), fcntl.LOCK_EX)
        try:
            previous = _analysis_latest(_analysis_entries(adir)).get(str(script))
            if previous:
                if not previous.get('job_id'):
                    return None, 'R-077: scheduler state unknown; prior submission unresolved'
                state, detail = _scheduler_status(root, previous['job_id'], BUILTINS[previous['executor']])
                if state is None:
                    return None, 'R-077: scheduler state unknown; resubmit refused: %s' % detail
                if not _scheduler_terminal(state):
                    return None, 'R-076: duplicate_submission; recorded job is %s' % state
            script_hash = _sha256(script)
            launcher = _analysis_launcher(adir, script, descriptor)
            entry = {'script': str(script), 'script_sha256': script_hash,
                     'launcher': str(launcher), 'launcher_sha256': _sha256(launcher),
                     'executor': descriptor['name'], 'submitted_at': time.time()}
            job, detail = _submit_once(root, launcher, descriptor)
            if job is None and isinstance(detail, SubmissionFailure):
                # No backend accepted this attempt; retain prior history unchanged.
                return job, detail
            entry['job_id'] = job
            if detail:
                entry['error'] = str(detail)
            with (adir / ANALYSIS_SUBMISSIONS).open('a') as record:
                record.write(json.dumps(entry, sort_keys=True) + '\n')
                record.flush()
                os.fsync(record.fileno())
            return job, detail
        except (OSError, ValueError, KeyError, TypeError) as exc:
            return None, 'R-135: stage-03 submission refused: %s' % exc



def _analysis_local_binding(root, entry):
    """A PID can be reused: its current local record must still name this launcher."""
    if entry.get('executor') != 'local':
        return True
    try:
        path = _local_jobs_dir(root) / (str(entry['job_id']) + '.json')
        local = json.loads(path.read_text(encoding='utf-8'))
        return isinstance(local, dict) and local.get('script') == entry['launcher']
    except (OSError, ValueError, KeyError, TypeError):
        return False


def analysis_execution_evidence(root, adir):
    """A marker alone proves nothing: bind every script's latest job and exact bytes."""
    adir = Path(adir).resolve()
    try:
        entries = _analysis_entries(adir)
        if not entries:
            raise ValueError('submission record missing or empty; analyses submitted before this fix must submit through the executor again')
        for entry in _analysis_latest(entries).values():
            for kind in ('script', 'launcher'):
                path = Path(entry[kind]).resolve()
                path.relative_to(adir)
                if _sha256(path) != entry[kind + '_sha256']:
                    raise ValueError(kind + ' SHA-256 changed since submit')
            if not entry.get('job_id'):
                raise ValueError('submission has no job id')
            if not _analysis_local_binding(root, entry):
                raise ValueError('local PID record differs from submission launcher')
            state, detail = _scheduler_status(root, entry['job_id'], BUILTINS[entry['executor']])
            if state != 'COMPLETED':
                raise ValueError('recorded job %s is %s: %s' % (entry['job_id'], state, detail))
    except (OSError, ValueError, KeyError, TypeError) as exc:
        return 'R-135: marker is not execution evidence: %s' % exc
    return None


def submit(config_root, script, descriptor=None):
    """R-076: reserve the prepared key before any scheduler side effect.

    A process crash or ambiguous scheduler response leaves the reservation in place,
    refusing a duplicate rather than guessing the first submission did not happen.
    The file lock serializes competing callers; this is not the Stage-3 durable table.
    """
    import wrapperlib as wl
    stage = Path(script).resolve().parent
    descriptor = descriptor if descriptor is not None else load(config_root)
    try:
        parts = stage.relative_to(Path(config_root).resolve()).parts
    except ValueError:
        return None, 'R-073: script is outside its project'
    if len(parts) >= 2 and parts[0] == '03_custom_analysis':
        return _submit_analysis(config_root, script, descriptor)
    # Keep row 4's preflight refusal intact.
    if len(parts) < 3 or parts[0] != '02_bioinformatics':
        return _submit_once(config_root, script, descriptor)
    problem = config_holds(config_root, stage, parts[1])
    if problem:
        return None, problem
    try:
        if Path(script).resolve() != stage / 'submit.sh':
            raise ValueError('expected generated submit.sh')
        key = prepared_key(config_root, stage)
    except (OSError, ValueError, KeyError, TypeError):
        return None, 'R-076: idempotency_key_missing_or_changed; run prepare'
    problems = validate(descriptor)
    if problems:
        return None, '; '.join(problems)
    directory = _records(config_root)
    directory.mkdir(exist_ok=True)
    with open(str(directory / '.lock'), 'a') as lock:
        fcntl.flock(lock.fileno(), fcntl.LOCK_EX)
        path = directory / (key + '.json')
        retry = None
        if path.exists():
            record = json.loads(path.read_text(encoding='utf-8'))
            state = recorded_state(record)
            if state.startswith('FAILED') or state == 'CANCELLED':
                problem = retry_refusal(config_root, stage, record, len(record.get('attempts', [])))
                if problem:
                    return None, problem
                retry = record
            else:
                return None, 'R-076: duplicate_submission; key already recorded (%s)' % state
        try:
            history = _stage_records(config_root, stage)
        except (OSError, ValueError, KeyError, TypeError) as exc:
            return None, 'R-135: invalid submission record: %s' % exc
        # A changed key is not permission to overlap work in the same run directory.
        if any(not _scheduler_terminal(recorded_state(old)) for old in history):
            return None, 'R-076: stage_job_unresolved; poll the recorded job before submitting corrected inputs'
        superseded = {old.get('supersedes_key') for old in history
                      if old.get('supersedes_key') != old['idempotency_key']}
        latest = [old for old in history if old['idempotency_key'] not in superseded]
        if len(latest) > 1:
            return None, 'R-135: conflicting stage submission records; owner reconciliation required'
        prior = latest[0] if latest else None
        if retry and (not prior or prior['idempotency_key'] != key):
            return None, 'R-152: retry_refused: attempt was superseded; reconcile before reverting inputs'
        previous = wl.read_status(stage)
        terminal = previous and previous.split(':', 1)[0] in wl.TERMINAL_STATES
        if terminal and not (prior and previous == recorded_state(prior) and
                             (previous.startswith('FAILED') or previous == 'CANCELLED')):
            return None, 'R-152: retry_policy_unresolved; terminal stage has no matching failed or cancelled record'
        record = {'idempotency_key': key, 'script': str(Path(script).resolve()),
                  'state': 'SUBMITTED', 'job_id': None, 'executor': descriptor['name'],
                  'submitted_at': time.time(), 'started_at': None,
                  'destructive': not (stage / 'params.yaml').is_file()}
        if prior and not retry:
            record['supersedes_key'] = prior['idempotency_key']
        if retry:
            if retry.get('supersedes_key'):
                record['supersedes_key'] = retry['supersedes_key']
            previous_attempt = dict(retry)
            previous_attempt.pop('attempts', None)
            record['attempts'] = retry.get('attempts', []) + [previous_attempt]
        _save_record(path, record)
        job, detail = _submit_once(config_root, script, descriptor)
        if job is None and isinstance(detail, SubmissionFailure):
            if retry:
                _save_record(path, retry)
            else:
                path.unlink()
            if not terminal:
                wl.write_status(stage, 'STALE')
            return job, detail
        record['job_id'] = job
        if job is None:
            record['state'] = 'STALE'
            record['error'] = detail
        _save_record(path, record)
        if job or not terminal:
            try:
                wl.write_status(stage, 'SUBMITTED' if job else 'STALE', submission_key=key)
            except wl.StatusRefusal as exc:
                record['status_error'] = str(exc)
                _save_record(path, record)
                return job, 'R-151: submitted job retained; writer refused: %s' % exc
        return job, detail


def _analysis_job_descriptor(config_root, job_id):
    for path in (Path(config_root) / '03_custom_analysis').glob('*/' + ANALYSIS_SUBMISSIONS):
        for entry in _analysis_entries(path.parent):
            if (entry.get('job_id') == str(job_id) and
                    _analysis_local_binding(config_root, entry)):
                return BUILTINS[entry['executor']]
    return None


def status(config_root, job_id, descriptor=None):
    """R-077: scheduler evidence updates only the job that submit recorded."""
    recorded = _analysis_job_descriptor(config_root, job_id)
    if recorded:
        return _scheduler_status(config_root, job_id, recorded)
    directory = _records(config_root)
    if not directory.exists():
        return _scheduler_status(config_root, job_id, descriptor)
    with open(str(directory / '.lock'), 'a') as lock:
        fcntl.flock(lock.fileno(), fcntl.LOCK_EX)
        return _status_locked(config_root, job_id, descriptor)


def _status_locked(config_root, job_id, descriptor, observed=None):
    import wrapperlib as wl
    path, record = _job_record(config_root, job_id)
    descriptor = descriptor if descriptor is not None else load(config_root)
    if record and descriptor.get('name') != record.get('executor'):
        return None, 'R-135: executor differs from the recorded submission'
    state, detail = observed if observed is not None else _scheduler_status(config_root, job_id, descriptor)
    if record:
        try:
            stage = _validate_record(config_root, path, record)
            history = _stage_records(config_root, stage)
        except (OSError, ValueError, KeyError, TypeError) as exc:
            return None, 'R-135: invalid submission record: %s' % exc
        started = scheduler_start(config_root, record, descriptor)
        if started is not None:
            record['started_at'] = started
            _save_record(path, record)
        if state == 'COMPLETED' and not (Path(record['script']).parent / 'run/.gars_run_complete').is_file():
            state, detail = 'ARTIFACT_MISSING', 'R-135: scheduler success without .gars_run_complete'
        if not _scheduler_terminal(recorded_state(record)):
            record['state'] = state or 'STALE'
            if state and state.startswith('FAILED'):
                record_failure(stage, record, state, detail or state)
            _save_record(path, record)
        previous = wl.read_status(stage)
        terminal = previous and previous.split(':', 1)[0] in wl.TERMINAL_STATES
        superseded = any(old.get('supersedes_key') == record['idempotency_key'] for old in history)
        if not terminal and not superseded:
            wl.write_status(stage, 'VALIDATING' if state == 'COMPLETED' else
                            ('SUBMITTED' if state == 'PENDING' else (state or 'STALE')),
                            submission_key=record['idempotency_key'])
        # Scheduler success is VALIDATING; collect alone publishes COMPLETE.
    return state, detail


# --- CLI ---------------------------------------------------------------------------------------


def emit(result, code):
    json.dump(result, sys.stdout, indent=2, sort_keys=True)
    sys.stdout.write("\n")
    return code


def main(argv=None):
    # `--workspace` is accepted on either side of the subcommand: the contracts write it
    # after (`... submit --workspace <project> <script>`), a shell habit writes it before.
    common = argparse.ArgumentParser(add_help=False)
    common.add_argument("--workspace", default=argparse.SUPPRESS,
                        help="the project directory that owns _config/")
    parser = argparse.ArgumentParser(description="The workspace's batch executor (0039).",
                                     parents=[common])
    parser.set_defaults(workspace=".")
    sub = parser.add_subparsers(dest="command")

    p_header = sub.add_parser("header", parents=[common],
                              help="print the generated submit.sh directives block")
    p_header.add_argument("--project", default="{project}")
    p_header.add_argument("--assay", default="{assay}")
    p_header.add_argument("--substage", default=".")
    for key in ("partition", "time", "cpus", "mem"):
        p_header.add_argument("--" + key, default=None)

    p_submit = sub.add_parser("submit", parents=[common],
                              help="submit a GENERATED submit.sh")
    p_submit.add_argument("script")

    p_status = sub.add_parser("status", parents=[common],
                              help="the state of a submitted job")
    p_status.add_argument("job_id")

    p_cancel = sub.add_parser("cancel", parents=[common], help="cancel a recorded job")
    p_cancel.add_argument("job_id")
    p_approve = sub.add_parser("approve-action", parents=[common], help="human-only job action approval")
    p_approve.add_argument("action", choices=('cancel', 'retry'))
    p_approve.add_argument("job_id")

    sub.add_parser("describe", parents=[common],
                   help="the resolved descriptor and any problems with it")

    args = parser.parse_args(argv)
    if not args.command:
        parser.print_help()
        return EXIT_USAGE

    root = Path(args.workspace)
    descriptor = load(root)
    problems = validate(descriptor)
    result = {"command": args.command, "executor": descriptor.get("name"),
              "descriptor": str(descriptor_path(root)),
              "descriptor_present": descriptor_path(root).is_file()}

    if args.command == "describe":
        result["resolved"] = descriptor
        result["problems"] = problems
        result["ok"] = not problems
        return emit(result, EXIT_OK if not problems else EXIT_REFUSED)

    if problems:
        result["problems"] = problems
        return emit(result, EXIT_REFUSED)

    if args.command == "header":
        cfg = {}
        for key in ("partition", "time", "cpus", "mem"):
            value = getattr(args, key)
            if value:
                cfg["compute." + key] = value
        result["header"] = header_lines(root, cfg, args.project, args.assay, args.substage,
                                        descriptor=descriptor)
        return emit(result, EXIT_OK)

    if args.command == "submit":
        job_id, detail = submit(root, args.script, descriptor=descriptor)
        if job_id is None:
            result["error"] = detail
            for reason, rule in (('duplicate_submission', 'R-076'),
                                 ('idempotency_key_missing_or_changed', 'R-076'),
                                 ('stage_job_unresolved', 'R-076'),
                                 ('retry_policy_unresolved', 'R-152'),
                                 ('retry_refused', 'R-152')):
                if reason in detail:
                    result['refusal'] = {'type': 'execution_refusal', 'rule': rule,
                                         'reason': reason}
                    return emit(result, EXIT_REFUSED)
            return emit(result, EXIT_FAILURE)
        recorded = _analysis_job_descriptor(root, job_id)
        if recorded:
            result["executor"] = recorded["name"]
        result["job_id"] = job_id
        result["ok"] = detail is None
        if detail:
            result["error"] = detail
        return emit(result, EXIT_OK if detail is None else EXIT_FAILURE)

    if args.command in ('cancel', 'approve-action'):
        try:
            ok, detail = (cancel(root, args.job_id, descriptor) if args.command == 'cancel'
                          else approve_action(root, args.job_id, args.action))
        except (OSError, ValueError, KeyError, TypeError) as exc:
            ok, detail = False, str(exc)
        result.update({'ok': ok, 'job_id': args.job_id})
        if detail:
            result['error'] = detail
        return emit(result, EXIT_OK if ok else EXIT_REFUSED)

    if args.command == "status":
        state, detail = status(root, args.job_id, descriptor=descriptor)
        if state is None:
            result["error"] = detail
            return emit(result, EXIT_FAILURE)
        recorded = _analysis_job_descriptor(root, args.job_id)
        if recorded:
            result["executor"] = recorded["name"]
        result["job_id"] = args.job_id
        result["state"] = state
        result["terminal"] = state in ("COMPLETED", "CANCELLED") or state.startswith("FAILED")
        return emit(result, EXIT_OK)

    return EXIT_USAGE


if __name__ == "__main__":
    sys.exit(main())
