#!/usr/bin/env python3
"""PreToolUse guard for a GARS workspace: the Scope Boundaries that CAN be mechanical, made so.

Wired by `.claude/settings.json`, which the agent harness loads when a session starts in the
workspace root (`gars/`). The harness sends one JSON object on stdin per tool call:

    {"tool_name": "...", "tool_input": {...}, "cwd": "..."}

Exit 0 allows the call. Exit 2 blocks it, and stderr is shown to the agent as the reason --
so every refusal names the rule and where it is written, the same way a contract template would.

Why this exists (decision 0022): prose scope boundaries were violated in real runs (0002, 0018).
The one rule that has never been violated is the one the filesystem enforces -- `files.csv` at
mode 0444. This hook generalizes that: a write the contracts forbid should fail at the moment it
is attempted, not be noticed two stages later. Prose remains for what genuinely cannot be
checked here (e.g. "do not read a colleague's directory").

Deliberately conservative: every deny below is an action NO contract ever instructs. A false
positive would block a legitimate stage step, which is worse than a miss -- misses are still
covered by prose and by 0444.

Runs on stock python 3.6.8, stdlib only, like every `_system/` helper.
"""

import fnmatch
import json
import os
import shlex
import sys

# Tools that write the file named in tool_input.file_path / notebook_path.
WRITE_TOOLS = ("Write", "Edit", "MultiEdit", "NotebookEdit")

# Workspace paths no session may write: the template ships them, `git pull` updates them.
# Relative to the workspace root, fnmatch patterns.
READ_ONLY = [
    "_system/*", "_system/**/*",
    "_references/*", "_references/**/*",
    "_templates/*", "_templates/**/*",
    ".claude/*", ".claude/**/*",
    "CLAUDE.md",
    "CONTEXT.md",
    "0*/CONTEXT.md",                      # stage contracts
    "0*/**/CONTEXT.md",                   # sub-stage contracts
    # Machine-owned project files: written by _system/ scripts, regenerated, never hand-edited.
    "projects/_index.md",
    "projects/*/00_data/*/files.csv",
    "projects/*/01_samplesheets/*",
]

# Bash substrings that install into the locked environments. The environments are pinned by
# lockfiles (_references/*.lock.txt); an ad-hoc install silently unpins them.
INSTALL_PATTERNS = (
    "pip install", "pip3 install", "python -m pip install", "python3 -m pip install",
    "conda install", "mamba install", "conda create", "mamba create",
    "conda update", "mamba update",
)

# Directories a Bash command must not use as a write target (redirection, tee, rm, mv, cp,
# sed -i). Checked against resolved targets, not the whole command line, so reading from or
# executing scripts in these directories stays allowed.
PROTECTED_PREFIXES = ("_system/", "_references/", "_templates/", ".claude/")


def workspace_root():
    root = os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd()
    return os.path.abspath(root)


def rel_to_root(path, root, cwd):
    """A path from tool input, made relative to the workspace root; None if outside it."""
    if not os.path.isabs(path):
        path = os.path.join(cwd or root, path)
    path = os.path.normpath(path)
    root = root.rstrip(os.sep) + os.sep
    if not path.startswith(root):
        return None
    return path[len(root):].replace(os.sep, "/")


def deny(message):
    sys.stderr.write(message + "\n")
    sys.exit(2)


def check_write_tool(tool_input, root, cwd):
    path = tool_input.get("file_path") or tool_input.get("notebook_path") or ""
    if not path:
        return
    rel = rel_to_root(path, root, cwd)
    if rel is None:
        return  # outside the workspace; prose boundaries govern there
    for pat in READ_ONLY:
        if fnmatch.fnmatch(rel, pat):
            if rel.startswith("projects/") and rel.endswith("files.csv"):
                deny("Blocked: %s is machine-owned (mode 0444). It is regenerated by "
                     "`_system/stage00_register.py finalize`; to change the cohort, edit "
                     "samples.csv instead. See the stage 00 contract, Definitions." % rel)
            if rel.startswith("projects/") and "/01_samplesheets/" in rel:
                deny("Blocked: %s is emitted by `_system/stage01_samplesheet.py`. Edit the "
                     "design (samples.csv) and re-run the emitter; never the emitted file. "
                     "See the stage 01 contract." % rel)
            if rel == "projects/_index.md":
                deny("Blocked: projects/_index.md is generated. Rebuild it with "
                     "`bash _system/build_projects_index.sh` instead of editing it.")
            deny("Blocked: %s is part of the GARS template, updated only by `git pull`. "
                 "A workspace session never edits contracts, references, templates or "
                 "_system/ code. See CLAUDE.md, Scope Boundaries." % rel)


def bash_write_targets(command):
    """Targets a shell command writes to: redirections, tee/rm/mv/cp/sed -i arguments.

    Best-effort token scan -- shlex, no shell emulation. Unparseable commands yield no
    targets (conservative in the allow direction; prose still governs)."""
    try:
        tokens = shlex.split(command, posix=True)
    except ValueError:
        return []
    targets = []
    i = 0
    while i < len(tokens):
        tok = tokens[i]
        if tok in (">", ">>", "1>", "2>", "&>") and i + 1 < len(tokens):
            targets.append(tokens[i + 1]); i += 2; continue
        if tok.startswith((">", ">>")) and len(tok) > 1 and not tok.startswith(">&"):
            targets.append(tok.lstrip(">")); i += 1; continue
        if tok == "tee":
            j = i + 1
            while j < len(tokens) and not tokens[j].startswith("-") \
                    and tokens[j] not in ("|", ";", "&&", "||"):
                targets.append(tokens[j]); j += 1
            i = j; continue
        if tok == "rm":
            for arg in tokens[i + 1:]:
                if arg in ("|", ";", "&&", "||"):
                    break
                if not arg.startswith("-"):
                    targets.append(arg)
            i += 1; continue
        if tok in ("mv", "cp"):
            args = []
            for arg in tokens[i + 1:]:
                if arg in ("|", ";", "&&", "||"):
                    break
                if not arg.startswith("-"):
                    args.append(arg)
            if len(args) >= 2:
                targets.append(args[-1])
            i += 1; continue
        if tok == "sed":
            rest = tokens[i + 1:]
            if any(a == "-i" or a.startswith("-i") for a in rest if a.startswith("-")):
                for arg in reversed(rest):
                    if arg in ("|", ";", "&&", "||"):
                        break
                    if not arg.startswith("-"):
                        targets.append(arg)
                        break
            i += 1; continue
        i += 1
    return targets


def check_bash(tool_input, root, cwd):
    command = tool_input.get("command") or ""
    lowered = " ".join(command.lower().split())

    for pat in INSTALL_PATTERNS:
        if pat in lowered:
            deny("Blocked: `%s` -- the gars-bio/gars-nxf environments are pinned by lockfiles "
                 "(_references/*.lock.txt). Installing ad hoc silently unpins them. If a tool "
                 "is missing, stop and report it; do not install. See _references/environment.md."
                 % pat)

    if "files.csv" in lowered:
        try:
            tokens = shlex.split(command, posix=True)
        except ValueError:
            tokens = command.split()
        verbs = {"chmod", "rm", "mv", "truncate", "shred"}
        if any(os.path.basename(t) in verbs or t in verbs for t in tokens[:1]) \
                or any(t in verbs for t in tokens):
            if any("files.csv" in t for t in tokens):
                deny("Blocked: files.csv is machine-owned (mode 0444) and regenerated by "
                     "`_system/stage00_register.py finalize`. Do not chmod, remove or move it; "
                     "to change the cohort, edit samples.csv. See decision 0018.")

    for target in bash_write_targets(command):
        rel = rel_to_root(target, root, cwd)
        if rel is None:
            continue
        if rel == "projects/_index.md":
            continue  # build_projects_index.sh legitimately redirects into it
        for prefix in PROTECTED_PREFIXES:
            if rel.startswith(prefix):
                deny("Blocked: the command writes to %s, which is part of the GARS template "
                     "(updated only by `git pull`). A workspace session never modifies "
                     "_system/, _references/, _templates/ or .claude/. See CLAUDE.md." % rel)
        if rel.startswith("projects/") and (rel.endswith("files.csv")
                                            or "/01_samplesheets/" in rel):
            deny("Blocked: the command writes to %s, which is machine-owned. It is produced "
                 "by a _system/ script; run the script instead of writing the file. See the "
                 "stage contract." % rel)


def main():
    try:
        payload = json.load(sys.stdin)
    except Exception:
        sys.exit(0)  # nothing to judge; allow
    tool = payload.get("tool_name") or ""
    tool_input = payload.get("tool_input") or {}
    cwd = payload.get("cwd") or ""
    root = workspace_root()

    if tool in WRITE_TOOLS:
        check_write_tool(tool_input, root, cwd)
    elif tool == "Bash":
        check_bash(tool_input, root, cwd)
    sys.exit(0)


if __name__ == "__main__":
    main()
