#!/usr/bin/env python3
"""GARS-authored spatial cluster-count wrapper -- sub-stage 02.02 for spatialvi.

Scaffolded by create-bioinformatics-skill, then filled on scrna-qc-cluster's shape. It does
ONE thing: count how many distinct clusters nf-core/spatialvi already assigned, per sample, by
reading the `obs` column the pipeline writes (`clusters`; `leiden_key_added = 'clusters'` in
the pipeline's workflow at the pin). It never clusters, never reads a `var` (gene) name, never
names a cell type, never lowers a threshold, and has NO fallback column list: an object whose
`obs` carries no `clusters` column is refused, naming the columns that do exist.

Why this is a sub-stage and not a sentence in a report: the 02.01 wrapper is stdlib-only and
cannot open an HDF5 file, so its exit gate proves only that every sample produced an object.
Here the analysis runs under `gars-bio`, so it can open the object and count -- and it writes a
machine-readable `run/summary.json` whose sample set this stdlib wrapper then checks against
the SAMPLESHEET, an independent source.

Division of labour, same as every 0028 wrapper: this file is stdlib-only and runs on stock
python; the analysis itself is a GENERATED script (`scripts/count_clusters.py`) executed under
`$GARS_PY` via the generated `submit.sh`.

  check    validates the config's compute.* keys, the samplesheet, that `--h5ad` resolves to
           one processed object per sample, and that the analysis environment carries
           anndata -- reported as a NAMED preconditions failure, never a raw ImportError.
  prepare  re-validates, then writes scripts/count_clusters.py, submit.sh and the
           reproducibility bundle. Deterministic bytes.
  collect  the exit gate: summary.json's sample set equals the samplesheet's (independent),
           clusters.tsv agrees with summary.json (internal consistency), the report is real.
           Writes OUTPUTS.tsv (table, report -- never an h5ad row) and STATUS.

Input `--h5ad` is the PATH the router resolved by artifact type (resolve_artifact.py):
either the results DIRECTORY 02.01 registered (per-sample file at
<dir>/<sample>/data/<sample>.h5ad) or a single .h5ad file for a one-sample samplesheet. This
wrapper never searches for it.

Runs on stock python 3.6.8, stdlib only.
"""

import argparse
import csv
import datetime
import json
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
import workspace as ws          # noqa: E402
import wrapperlib as wl         # noqa: E402
from wrapperlib import (EXIT_OK, EXIT_FAILURE, EXIT_REFUSED, EXIT_USAGE,   # noqa: E402
                        emit, fail)

WORKSPACE = Path(__file__).resolve().parents[3]

ASSAY = "spatialvi"
SUBSTAGE = "02_spatial-cluster-count"

# The one obs column this skill reads. nf-core/spatialvi writes it (`leiden_key_added =
# 'clusters'` at the pin), and the recorded run read exactly this name. There is deliberately
# no list of alternatives: a fallback that silently picked another column would report a
# count from a clustering nobody asked for.
OBS_COLUMN = "clusters"

# The packages the generated analysis imports. Named here so `check` can refuse by name.
ANALYSIS_IMPORTS = ("anndata",)

SAMPLESHEET_HEADER = ["sample", "spaceranger_dir"]

# The compute.* keys the generated submit header reads (executorlib.header_lines). Nothing
# scientific: this skill has no thresholds.
REQUIRED_KEYS = ("compute.partition", "compute.time", "compute.cpus", "compute.mem")

# The analysis, generated verbatim into scripts/count_clusters.py at prepare time. A template
# string rather than a shipped file so the wrapper is one self-contained unit and the script
# version is pinned by the template version in the manifest. %%-formatted (no f-strings: the
# helpers run on stock python 3.6.8); every literal percent inside is doubled. The script takes
# no arguments and embeds its exact inputs -- reproducible by `python count_clusters.py` alone.
COUNT_CLUSTERS_TEMPLATE = '''#!/usr/bin/env python
"""Cluster COUNT per sample for %(project)s/%(assay)s, generated by the spatial-cluster-count
wrapper. Do not hand-edit: regenerate with `prepare`.

Reads the obs column %(obs_column)r that nf-core/spatialvi wrote and reports how many distinct
values it holds. It does not cluster, does not name a cell type, never reads a var (gene)
name, and has no fallback column: an object without the column is refused (exit 2) naming the
columns it does have.

Exit codes: 0 ok, 1 failure, 2 refused, 3 usage.
"""
import json
import os
import sys

import anndata

INPUTS = %(inputs)r
OUT = %(out)r
OBS_COLUMN = %(obs_column)r


def emit(result, code):
    sys.stdout.write(json.dumps(result, indent=2, sort_keys=True) + "\\n")
    return code


def cluster_key(cluster_id):
    """Numeric ids sort numerically, anything else lexically after them. Deterministic."""
    return (0, int(cluster_id)) if cluster_id.isdigit() else (1, cluster_id)


def main():
    result = {"tool": "count_clusters", "obs_column": OBS_COLUMN, "ok": False}
    os.makedirs(OUT, exist_ok=True)
    per_sample = {}
    per_cluster = {}
    for sample, path in INPUTS:
        if not os.path.isfile(path):
            result["error"] = "no such file for sample %%s: %%s" %% (sample, path)
            return emit(result, 2)
        try:
            adata = anndata.read_h5ad(path)
        except Exception as exc:                 # the message is the point
            result["error"] = "could not read %%s (%%s): %%s" %% (path, sample, exc)
            return emit(result, 1)
        obs = adata.obs
        if OBS_COLUMN not in obs.columns:
            result["error"] = (
                "sample %%s: obs has no %%r column, so there is no cluster count to report. "
                "This skill reads only the column the pipeline writes and never falls back "
                "to another. Columns present: %%s"
                %% (sample, OBS_COLUMN, ", ".join(str(c) for c in obs.columns) or "(none)"))
            result["obs_columns"] = [str(c) for c in obs.columns]
            return emit(result, 2)
        values = obs[OBS_COLUMN]
        n_missing = int(values.isna().sum())
        if n_missing:
            result["error"] = (
                "sample %%s: %%d spot(s) carry no value in obs[%%r]. This skill counts only "
                "what the pipeline assigned and does not guess." %% (sample, n_missing, OBS_COLUMN))
            return emit(result, 2)
        # nunique() over the VALUES, never a categorical's declared categories: an unused
        # category would inflate the count into a number no spot supports. The per-cluster
        # tally is over the same string-cast values for the same reason.
        n_clusters = int(values.nunique())
        n_obs = int(obs.shape[0])
        counts = values.astype(str).value_counts()
        per_cluster[sample] = {str(k): int(v) for k, v in counts.items() if int(v) > 0}
        per_sample[sample] = {"n_clusters": n_clusters, "n_obs": n_obs}

    # --- clusters.tsv: sample, cluster (the pipeline's own id, never a name), n_spots -----------
    with open(os.path.join(OUT, "clusters.tsv"), "w") as fh:
        fh.write("sample\\tcluster\\tn_spots\\n")
        for sample, _ in INPUTS:
            for cid in sorted(per_cluster[sample], key=cluster_key):
                fh.write("%%s\\t%%s\\t%%d\\n" %% (sample, cid, per_cluster[sample][cid]))

    # --- summary.json: the machine-readable numbers the exit gate checks ------------------------
    # Top-level n_clusters / n_obs exist ONLY for a single sample. Cluster ids are per sample
    # and not comparable across samples, so with several there is no honest total to write.
    summary = {"obs_column": OBS_COLUMN, "samples": per_sample}
    if len(INPUTS) == 1:
        only = per_sample[INPUTS[0][0]]
        summary["n_clusters"] = only["n_clusters"]
        summary["n_obs"] = only["n_obs"]
    with open(os.path.join(OUT, "summary.json"), "w") as fh:
        json.dump(summary, fh, indent=2, sort_keys=True)
        fh.write("\\n")

    with open(os.path.join(OUT, "report.md"), "w") as fh:
        fh.write("# Cluster count -- %(project)s (%(assay)s)\\n\\n")
        fh.write("Column read: `obs[%%r]`, as written by nf-core/spatialvi.\\n\\n" %% OBS_COLUMN)
        fh.write("| Sample | Spots | Clusters | File read |\\n|---|---|---|---|\\n")
        for sample, path in INPUTS:
            fh.write("| %%s | %%d | %%d | `%%s` |\\n"
                     %% (sample, per_sample[sample]["n_obs"],
                        per_sample[sample]["n_clusters"], path))
        fh.write("\\nPer-cluster spot counts are in `clusters.tsv`; the cluster column is the "
                 "pipeline's own id.\\n\\n")
        fh.write("## What this skill deliberately does not do\\n\\n"
                 "- It did not cluster anything; the assignment is the pipeline's.\\n"
                 "- It did not name any cluster a cell type or a tissue region.\\n"
                 "- It did not read a `var` (gene) name.\\n"
                 "- It did not fall back to another obs column; only `%%s` is read.\\n"
                 "- It has no threshold, so none was lowered.\\n" %% OBS_COLUMN)
        if len(INPUTS) > 1:
            fh.write("\\nCluster ids are per sample and not comparable across samples, so no "
                     "total is reported.\\n")

    # The completion marker, written LAST: collect gates on it.
    with open(os.path.join(OUT, ".gars_run_complete"), "w") as fh:
        fh.write("count_clusters\\n")

    result.update({"ok": True, "summary": summary})
    return emit(result, 0)


if __name__ == "__main__":
    sys.exit(main())
'''


def paths_for(project):
    return {"substage": project / "02_bioinformatics" / ASSAY / SUBSTAGE,
            "config": project / "_config" / ("%s.yaml" % ASSAY),
            "samplesheet": project / "01_samplesheets" / ("%s_samplesheet.csv" % ASSAY)}


def processed_h5ad(results, sample):
    """The per-sample PROCESSED object under 02.01's results directory -- the same name the
    02.01 wrapper builds. `<sample>-raw.h5ad` sits beside it and is never a fallback."""
    return results / sample / "data" / ("%s.h5ad" % sample)


def analysis_python():
    """The interpreter the generated script runs under, from the environment's $GARS_PY."""
    import os
    return os.environ.get("GARS_PY", "python3")


def check_analysis_env(fails):
    """Refuse by NAME when the analysis environment lacks a package.

    The assay map's rule: a sub-stage that finds a requirement missing reports it as a
    preconditions failure naming the requirement, rather than surfacing a raw ImportError
    inside a Slurm job. `gars-bio` carries anndata by pin (gars-bio.lock.txt); it is never
    installed at run time.
    """
    py = analysis_python()
    # `import importlib` alone does NOT bring in importlib.util -- the submodule must be
    # imported explicitly (the sibling's probe crashed on exactly that once).
    probe = ("import importlib.util,sys;"
             "missing=[m for m in %r if importlib.util.find_spec(m) is None];"
             "sys.stdout.write(','.join(missing))" % (list(ANALYSIS_IMPORTS),))
    try:
        out = subprocess.run([py, "-c", probe], stdout=subprocess.PIPE,
                             stderr=subprocess.PIPE)
    except OSError as exc:
        fails.append(fail("preconditions",
                          "cannot run the analysis interpreter %r: %s. It comes from "
                          "$GARS_PY, set by the workspace environment." % (py, exc)))
        return
    if out.returncode != 0:
        fails.append(fail("preconditions",
                          "the analysis interpreter %r could not be probed: %s"
                          % (py, out.stderr.decode("utf-8", "replace").strip()[:200])))
        return
    missing = [m for m in out.stdout.decode().strip().split(",") if m]
    if missing:
        import os
        if os.environ.get("GARS_PY") is None:
            # The probe fell back to `python3`: the likely cause is an unsourced environment,
            # not a broken one, so name that first.
            fails.append(fail("preconditions",
                              "GARS_PY is not set, so `python3` was probed and it is missing: "
                              "%s. Source gars-env.sh (the workspace environment) or set "
                              "GARS_PY before check; if the package is still missing then, "
                              "rebuild the environment from gars-bio.lock.txt, never "
                              "pip-install at run time." % ", ".join(missing)))
            return
        fails.append(fail("preconditions",
                          "the analysis environment (%s) is missing: %s. anndata is pinned in "
                          "gars-bio.lock.txt; rebuild the environment from the lockfile, never "
                          "pip-install at run time." % (py, ", ".join(missing))))


def resolve_inputs(h5ad_arg, samples, fails):
    """`--h5ad` -> [(sample, path)] in sorted sample order (wl.samplesheet_samples), or
    failures naming what is wrong.

    A DIRECTORY is what the router hands over: 02.01 registers its results directory as the
    `h5ad` artifact (the set is the artifact), and the per-sample object sits at
    <dir>/<sample>/data/<sample>.h5ad. A FILE is what a single-sample driver hands over; it
    serves exactly one sample, so a samplesheet with more is refused rather than guessed at.
    """
    if not h5ad_arg:
        fails.append(fail("preconditions",
                          "--h5ad was not supplied; stage 02's router resolves it by artifact "
                          "type from 02.01's OUTPUTS.tsv"))
        return []
    if not samples:
        return []                               # the samplesheet failure is already reported
    p = Path(h5ad_arg)
    if p.is_dir():
        pairs, missing = [], []
        for s in samples:
            f = processed_h5ad(p, s)
            if not f.is_file() or f.stat().st_size == 0:
                missing.append("%s (expected %s)" % (s, f))
            else:
                pairs.append((s, f))
        if missing:
            fails.append(fail("preconditions",
                              "no processed <sample>.h5ad under %s for: %s. A -raw.h5ad beside "
                              "it is the pre-analysis object and is never substituted."
                              % (p, "; ".join(missing))))
        return pairs
    if p.is_file():
        if p.stat().st_size == 0:
            fails.append(fail("preconditions", "%s is zero bytes" % p))
            return []
        if len(samples) != 1:
            fails.append(fail("preconditions",
                              "--h5ad names a single file but the samplesheet has %d samples "
                              "(%s); one file serves exactly one sample -- hand over the "
                              "results directory 02.01 registered instead"
                              % (len(samples), ", ".join(samples))))
            return []
        return [(samples[0], p)]
    fails.append(fail("preconditions", "no h5ad file or directory at %s" % p))
    return []


def run_checks(project, h5ad_path):
    fails = []
    paths = paths_for(project)
    cfg = {}
    if not paths["config"].is_file():
        fails.append(fail("preconditions", "no config at _config/%s.yaml" % ASSAY))
    else:
        cfg = wl.read_config(paths["config"])
        wl.check_config_common(cfg, REQUIRED_KEYS, fails)

    samples = []
    if not paths["samplesheet"].is_file():
        fails.append(fail("preconditions",
                          "no samplesheet at 01_samplesheets/%s -- the exit gate checks the "
                          "analysis's sample set against it" % paths["samplesheet"].name))
    else:
        # Header only: the spaceranger_dir column is 02.01's business, not this skill's.
        wl.check_samplesheet(paths["samplesheet"], SAMPLESHEET_HEADER, fails,
                             path_columns=())
        samples = wl.samplesheet_samples(paths["samplesheet"])
        if not samples:
            fails.append(fail("samplesheet", "the samplesheet lists no samples"))

    inputs = resolve_inputs(h5ad_path, samples, fails)

    check_analysis_env(fails)
    wl.check_run_dir(paths["substage"], fails)
    paths["inputs"] = inputs
    paths["samples"] = samples
    return fails, cfg, paths


def cmd_check(args):
    project = Path(args.project)
    result = {"command": "check", "ok": False, "assay": ASSAY, "failures": []}
    if not project.is_dir():
        result["error"] = "no such project: %s" % project
        return emit(result, EXIT_USAGE)
    fails, cfg, paths = run_checks(project, args.h5ad)
    result["failures"] = fails
    result["ok"] = not fails
    result["inputs"] = [{"sample": s, "h5ad": str(p)} for s, p in paths["inputs"]]
    preflight = paths["substage"] / "preflight"
    preflight.mkdir(parents=True, exist_ok=True)
    with ws.atomic_open(preflight / "check_result.json") as fh:
        json.dump({"ok": result["ok"], "failures": fails,
                   "wrapper": "spatial-cluster-count"}, fh, indent=2, sort_keys=True)
    result["wrote"] = str((preflight / "check_result.json").relative_to(project))
    return emit(result, EXIT_OK if result["ok"] else EXIT_FAILURE)


def cmd_prepare(args):
    project = Path(args.project)
    result = {"command": "prepare", "ok": False, "assay": ASSAY, "failures": []}
    if not project.is_dir():
        result["error"] = "no such project: %s" % project
        return emit(result, EXIT_USAGE)
    fails, cfg, paths = run_checks(project, args.h5ad)
    if fails:
        result["failures"] = fails
        result["error"] = "checks failed; nothing written. Run `check` for the same detail."
        return emit(result, EXIT_FAILURE)

    substage = paths["substage"]
    (substage / "scripts").mkdir(parents=True, exist_ok=True)
    (substage / "logs").mkdir(exist_ok=True)

    # Absolute paths throughout: submit.sh runs the script from run/, so anything relative
    # here resolves against the wrong directory.
    inputs = [(s, str(p.resolve())) for s, p in paths["inputs"]]
    script = COUNT_CLUSTERS_TEMPLATE % {
        "project": project.resolve().name, "assay": ASSAY,
        "inputs": inputs, "out": str((substage / "run").resolve()),
        "obs_column": OBS_COLUMN}
    with ws.atomic_open(substage / "scripts" / "count_clusters.py") as fh:
        fh.write(script)

    body = ('# Cluster count per sample, under gars-bio (anndata)\n'
            '"$GARS_PY" "%s/scripts/count_clusters.py"' % str(substage.resolve()))
    wl.write_submit_sh(substage, WORKSPACE, cfg, project.resolve().name,
                       "%s-clusters" % ASSAY, body)
    repro_inputs = {"config": paths["config"], "samplesheet": paths["samplesheet"]}
    for s, p in paths["inputs"]:
        repro_inputs["h5ad_%s" % s] = p
    wl.write_reproducibility(substage, "spatial-cluster-count", WORKSPACE, repro_inputs,
                             [("h5ad", str(args.h5ad)),
                              ("obs_column", OBS_COLUMN),
                              ("samples", ",".join(s for s, _ in inputs))])

    result.update({"ok": True,
                   "wrote": ["scripts/count_clusters.py", "submit.sh",
                             "reproducibility/manifest.json", "reproducibility/commands.sh"],
                   "inputs": [{"sample": s, "h5ad": p} for s, p in inputs],
                   "submit": str((substage / "submit.sh").resolve())})
    return emit(result, EXIT_OK)


def count_of(entry, key, sample, fails):
    """summary.json's `key` for `sample` as an int, or None after a named `summary` failure.

    The values are read straight from a file the analysis wrote; a string or a float there
    must surface as a failure the JSON lists, not as a ValueError traceback from int().
    bool is excluded explicitly because it is an int subclass.
    """
    value = entry.get(key)
    if isinstance(value, bool) or not isinstance(value, int):
        fails.append(fail("summary", "sample %s: %s in summary.json is not an integer: %r"
                          % (sample, key, value)))
        return None
    return value


def cmd_collect(args):
    project = Path(args.project)
    result = {"command": "collect", "ok": False, "assay": ASSAY, "failures": []}
    if not project.is_dir():
        result["error"] = "no such project: %s" % project
        return emit(result, EXIT_USAGE)
    paths = paths_for(project)
    substage = paths["substage"]
    if not (substage / "run" / ".gars_run_complete").is_file():
        result["error"] = ("run/.gars_run_complete is absent: the analysis has not finished "
                           "(or crashed before the marker). collect gates on completion, it "
                           "does not wait for it.")
        return emit(result, EXIT_REFUSED)

    run = substage / "run"
    fails = []

    # --- the summary --------------------------------------------------------------------------
    summary_path = run / "summary.json"
    summary = None
    if not summary_path.is_file():
        fails.append(fail("summary", "missing %s -- the analysis writes it before the "
                                     "marker, so its absence means the run did not finish "
                                     "cleanly" % summary_path))
    else:
        try:
            summary = json.loads(summary_path.read_text(encoding="utf-8"))
        except ValueError as exc:
            fails.append(fail("summary", "summary.json is not valid JSON: %s" % exc))
    per_sample = {}
    if summary is not None:
        per_sample = summary.get("samples") or {}
        if not isinstance(per_sample, dict) or not per_sample:
            fails.append(fail("summary", "summary.json carries no per-sample counts"))
            per_sample = {}
        if summary.get("obs_column") != OBS_COLUMN:
            fails.append(fail("summary",
                              "summary.json says the column read was %r, not %r -- this "
                              "skill reads only the column the pipeline writes"
                              % (summary.get("obs_column"), OBS_COLUMN)))

    # --- INDEPENDENT check: the sample set, against the samplesheet ---------------------------
    # The analysis reports its own sample set; a self-reported set trusted on its own gates
    # nothing. The samplesheet is the independent source: every sample it lists must be
    # counted, and nothing it does not list may appear.
    expected = []
    if not paths["samplesheet"].is_file():
        fails.append(fail("preconditions",
                          "no samplesheet at 01_samplesheets/%s -- the exit gate cannot check "
                          "the sample set without it" % paths["samplesheet"].name))
    else:
        expected = wl.samplesheet_samples(paths["samplesheet"])
    if per_sample and expected:
        got = sorted(per_sample)
        lost = sorted(set(expected) - set(got))
        unknown = sorted(set(got) - set(expected))
        if lost:
            fails.append(fail("summary",
                              "samplesheet sample(s) with no count in summary.json: %s"
                              % ", ".join(lost)))
        if unknown:
            fails.append(fail("summary",
                              "summary.json reports sample(s) the samplesheet does not list: "
                              "%s" % ", ".join(unknown)))
    # The counts, coerced ONCE per sample: a value that is not an integer is a named `summary`
    # failure, never a traceback (the contract promises the JSON lists every failure).
    counts = {}
    for s in sorted(per_sample):
        entry = per_sample[s] if isinstance(per_sample[s], dict) else {}
        n_obs = count_of(entry, "n_obs", s, fails)
        n_clusters = count_of(entry, "n_clusters", s, fails)
        counts[s] = (n_clusters, n_obs)
        if n_obs is not None and n_obs <= 0:
            fails.append(fail("summary", "sample %s has no spots. That is a result to report; "
                                         "this skill has no threshold to lower." % s))
        if n_clusters is not None and n_clusters <= 0:
            fails.append(fail("summary", "sample %s has no clusters" % s))

    # --- INTERNAL consistency: clusters.tsv against summary.json ------------------------------
    # Both files were written by the same script from the same values. Agreement proves the
    # table is whole and was not truncated or edited; it proves nothing about the pipeline's
    # clustering, and is not the independent check above.
    table = run / "clusters.tsv"
    rows_per_sample, spots_per_sample = {}, {}
    if not table.is_file() or table.stat().st_size == 0:
        fails.append(fail("table", "missing or empty %s" % table))
    else:
        with table.open() as fh:
            rows = list(csv.reader(fh, delimiter="\t"))
        if not rows or rows[0] != ["sample", "cluster", "n_spots"]:
            fails.append(fail("table", "clusters.tsv header is %r, expected "
                                       "sample, cluster, n_spots"
                              % (",".join(rows[0]) if rows else "missing")))
        else:
            for r in rows[1:]:
                if len(r) != 3 or not r[0].strip() or not r[1].strip():
                    fails.append(fail("table", "malformed row in clusters.tsv: %r" % r))
                    continue
                try:
                    n = int(r[2])
                except ValueError:
                    fails.append(fail("table", "non-integer n_spots in clusters.tsv: %r" % r))
                    continue
                rows_per_sample[r[0]] = rows_per_sample.get(r[0], 0) + 1
                spots_per_sample[r[0]] = spots_per_sample.get(r[0], 0) + n
            for s in sorted(per_sample):
                n_clusters, n_obs = counts[s]
                n_rows = rows_per_sample.get(s, 0)
                n_spots = spots_per_sample.get(s, 0)
                # A count already refused above (not an integer) has nothing to compare.
                if n_clusters is not None and n_rows != n_clusters:
                    fails.append(fail("table",
                                      "clusters.tsv has %d row(s) for %s but summary.json says "
                                      "%d clusters -- the two disagree, so one is not whole"
                                      % (n_rows, s, n_clusters)))
                if n_obs is not None and n_spots != n_obs:
                    fails.append(fail("table",
                                      "clusters.tsv spots for %s sum to %d but summary.json "
                                      "says n_obs %d" % (s, n_spots, n_obs)))
            extra = sorted(set(rows_per_sample) - set(per_sample))
            if extra:
                fails.append(fail("table", "clusters.tsv names sample(s) absent from "
                                           "summary.json: %s" % ", ".join(extra)))

    report = run / "report.md"
    if not report.is_file() or report.stat().st_size == 0:
        fails.append(fail("report", "missing or empty %s" % report))

    if fails:
        result["failures"] = fails
        return emit(result, EXIT_FAILURE)

    # Never an h5ad row: this sub-stage produces no object, and a row here would shadow
    # 02.01's for every later consumer (the resolver takes the newest native match).
    outputs = [("table", "native", "run/clusters.tsv"),
               ("report", "native", "run/report.md")]
    with ws.atomic_open(substage / "OUTPUTS.tsv") as fh:
        fh.write("# type\trole\tpath\n")
        for typ, role, path in outputs:
            fh.write("%s\t%s\t%s\n" % (typ, role, path))

    now = datetime.datetime.now().strftime("%Y-%m-%dT%H:%M:%S")
    with ws.atomic_open(substage / "STATUS") as fh:
        fh.write("COMPLETE %s\n" % now)

    version = ws.template_version(WORKSPACE)
    model = args.model or "unknown"
    counts = ", ".join("%s: %s clusters / %s spots"
                       % (s, per_sample[s].get("n_clusters"), per_sample[s].get("n_obs"))
                       for s in sorted(per_sample))
    entry = "\n".join([
        "## <ISO-8601 date> — 02_bioinformatics/%s/%s — cluster count complete"
        % (ASSAY, SUBSTAGE),
        "",
        "Template version: %s" % version,
        "Model: %s" % model,
        "Method: count of distinct values in obs[%r] as written by nf-core/spatialvi, read "
        "with anndata via the gars spatial-cluster-count wrapper; nothing re-clustered, "
        "nothing named, no gene read" % OBS_COLUMN,
        "Obs column: %s" % OBS_COLUMN,
        "Matrix supplied by: %s" % (args.h5ad_from or "unknown"),
        "Samples: %d (%s)" % (len(per_sample), counts),
        "Outputs: " + ", ".join("`%s`" % t for t, _, _ in outputs),
    ])
    result.update({"ok": True,
                   "outputs": [{"type": t, "role": r, "path": p} for t, r, p in outputs],
                   "samples": per_sample, "obs_column": OBS_COLUMN,
                   "template_version": version, "model": model, "history_entry": entry})
    if "n_clusters" in summary:
        result["n_clusters"] = summary["n_clusters"]
        result["n_obs"] = summary["n_obs"]
    return emit(result, EXIT_OK)


def main(argv=None):
    # allow_abbrev=False on EVERY parser: argparse's prefix matching would otherwise bind
    # `collect --h5ad <path>` to `--h5ad-from` and record an object path as the supplying
    # sub-stage in HISTORY.md. The flag does not propagate from the parent to a sub-parser,
    # so each add_parser carries it too.
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0], allow_abbrev=False)
    sub = ap.add_subparsers(dest="cmd")
    for name in ("check", "prepare", "collect"):
        p = sub.add_parser(name, allow_abbrev=False)
        p.add_argument("--project", required=True)
        if name in ("check", "prepare"):
            p.add_argument("--h5ad", default=None,
                           help="the h5ad artifact stage 02 resolved by type: 02.01's results "
                                "directory, or one .h5ad file for a one-sample samplesheet")
        if name == "collect":
            p.add_argument("--model", default="unknown",
                           help="the exact model id of the agent executing this sub-stage "
                                "(decision 0024)")
            p.add_argument("--h5ad-from", default=None,
                           help="the sub-stage that supplied the matrix, for HISTORY.md")
    args = ap.parse_args(argv)
    if not args.cmd:
        ap.print_help(sys.stderr)
        return EXIT_USAGE
    return {"check": cmd_check, "prepare": cmd_prepare, "collect": cmd_collect}[args.cmd](args)


if __name__ == "__main__":
    sys.exit(main())
