"""R-080/R-081: attacks against PostgreSQL 16 as the actual restricted login."""
import os
import re
from pathlib import Path
import subprocess
import sys
import unittest
from unittest import mock
from support import REPO, GARS, module, run

SQL = GARS / '_system/claims/claims.sql'
# Parent red is an import error naming the missing production SQL file.
SCHEMA = SQL.read_text()
FIXTURE = GARS / 'tests/fixtures/claims'
row5 = module(REPO / 'tests/test_row05_backup.py', 'row07_row5_support')


def insert(cid=99, rid=1, evidence='ARRAY[1]::bigint[]', bio="'{}'", risk="'{}'"):
    return ("SELECT claims.claim_insert(%s,%s,'OBSERVATION','Synthetic observation',"
            "%s,%s,'release-A','workflow-v1',%s);" % (cid, rid, bio, risk, evidence))


@row5.needs_scratch
class ClaimConstraintTests(unittest.TestCase):
    # Reuse row 5's container startup, scratch password, loopback readiness and teardown.
    compose = classmethod(row5.Row05DatabaseTests.compose.__func__)

    @classmethod
    def setUpClass(cls):
        row5.Row05DatabaseTests.setUpClass.__func__(cls)
        if cls.probe:
            probe = cls.probe
            row5.Row05DatabaseTests.tearDownClass.__func__(cls)
            if (os.environ.get('GARS_TEST_NO_CONTAINER') != '1' and
                    os.environ.get('CI', '').lower() in ('1', 'true', 'yes')):
                raise AssertionError('required container probe failed: ' + probe)
            raise unittest.SkipTest('container probe: ' + probe)

    @classmethod
    def tearDownClass(cls):
        row5.Row05DatabaseTests.tearDownClass.__func__(cls)

    def client(self, writer=False, db='source', transaction=False):
        user = 'gars_claims_writer' if writer else self.env['PGUSER']
        argv = self.command + ['exec', '-T', 'db', 'sh', '-c',
            'export PGPASSWORD="$(cat /run/secrets/pg_password)"; '
            'export PGCONNECT_TIMEOUT=5; exec "$@"', 'row07-test',
            'psql', '-h', self.env['PGHOST'], '-p', self.env['PGPORT'], '-U', user,
            '-d', db, '-X', '-A', '-t', '-v', 'ON_ERROR_STOP=1', '-v', 'VERBOSITY=verbose']
        if transaction:
            argv += ['-1']
        # stdin / -f is required for psql -1 to wrap the whole schema.
        argv += ['-f', '-']
        return argv

    def sql(self, query, writer=False, db='source', transaction=False):
        argv = self.client(writer, db, transaction)
        if writer:
            query = """DO $$ BEGIN
                IF current_user <> 'gars_claims_writer' OR
                   (SELECT rolsuper FROM pg_roles WHERE rolname = current_user) THEN
                    RAISE EXCEPTION 'attack principal is not the restricted writer';
                END IF;
                RAISE NOTICE 'writer identity verified';
            END $$;
            """ + query
        return subprocess.run(argv, input=query, env=row5.scrubbed_env(self.env),
                              stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                              universal_newlines=True, timeout=60)

    def ok(self, query, **kwargs):
        p = self.sql(query, **kwargs)
        self.assertEqual(p.returncode, 0, p.stderr)
        return p.stdout

    def setUp(self):
        self.ok('DROP DATABASE IF EXISTS source;', db='postgres')
        self.ok('CREATE DATABASE source;', db='postgres')
        self.ok(SCHEMA, transaction=True)
        # The only password value is generated by row 5 in scratch; never a source literal.
        password = self.password.read_text()
        self.assertIsNotNone(re.fullmatch(r'[0-9a-f]{32}', password), 'scratch password must be generated UUID hex')
        self.ok("ALTER ROLE gars_claims_writer PASSWORD '%s';" % password)
        self.ok((FIXTURE / 'fixture.sql').read_text(), transaction=True)

    def orphan_count(self):
        value = self.ok("SELECT count(*) FILTER (WHERE NOT EXISTS (SELECT FROM claims.claim_evidence ce "
                        "WHERE ce.claim_id = c.id)) || '/' || count(*) FROM claims.claim c;").strip()
        orphan, total = map(int, value.split('/'))
        self.assertEqual(orphan, 0)
        self.assertGreater(total, 0)
        print('orphan claims: ' + value, flush=True)

    def attack(self, query, reason, writer=True):
        if not writer:
            query = "SET ROLE gars_claims_owner; " + query
        p = self.sql(query, writer=writer)
        if writer:
            self.assertIn('writer identity verified', p.stderr)
        self.assertNotEqual(p.returncode, 0, 'attack committed: ' + query)
        self.assertIn(reason, p.stderr, 'refused for the wrong reason: ' + p.stderr)
        self.orphan_count()

    def test_direct_writes_and_privilege_escalation(self):
        attacks = [
            "INSERT INTO claims.claim VALUES (99,1,'OBSERVATION','x','{}','{}','r','w');",
            "INSERT INTO claims.run VALUES (99,'q','p','h',false);",
            'UPDATE claims.run SET exploratory=false;',
            'DELETE FROM claims.evidence WHERE id=1;',
            'TRUNCATE claims.claim_evidence;',
            'TRUNCATE claims.claim, claims.claim_evidence;',
            'ALTER TABLE claims.claim DISABLE TRIGGER ALL;',
            'DROP TRIGGER claim_has_evidence ON claims.claim;',
            'SET session_replication_role=replica;',
            'SET ROLE gars_claims_owner;',
            'DELETE FROM claims.claim;',
        ]
        for query in attacks:
            with self.subTest(query=query):
                self.attack(query, '42501')

    def test_empty_evidence_insert(self):
        for ids in ('ARRAY[]::bigint[]', 'NULL'):
            self.attack(insert(evidence=ids), 'requires at least one evidence link')

    def test_deferred_insert_and_owner_whole_claim_deletion(self):
        self.attack("BEGIN; INSERT INTO claims.claim VALUES (99,1,'OBSERVATION','x','{}','{}','r','w'); COMMIT;",
                    'requires at least one evidence link', writer=False)
        # An immediate-only INSERT trigger would refuse this legitimate transaction.
        self.ok("BEGIN; INSERT INTO claims.claim VALUES (99,1,'OBSERVATION','x','{}','{}','r','w');"
                'INSERT INTO claims.claim_evidence VALUES (99,1); COMMIT;')
        self.ok('BEGIN; DELETE FROM claims.claim_evidence WHERE claim_id=99; '
                'DELETE FROM claims.claim WHERE id=99; COMMIT;')
        self.orphan_count()

    def test_delete_links_same_and_later_transactions(self):
        self.attack('BEGIN; ' + insert() + ' DELETE FROM claims.claim_evidence WHERE claim_id=99; COMMIT;',
                    'requires at least one evidence link')
        self.ok(insert(), writer=True)
        self.attack('BEGIN; DELETE FROM claims.claim_evidence WHERE claim_id=99; COMMIT;',
                    'requires at least one evidence link')
        # Removing one of two links is legitimate; removing the last one later is not.
        self.ok('DELETE FROM claims.claim_evidence WHERE claim_id=1 AND evidence_id=3;', writer=True)
        self.attack('DELETE FROM claims.claim_evidence WHERE claim_id=1;',
                    'requires at least one evidence link')

    def test_update_links_checks_old_and_new(self):
        self.attack('UPDATE claims.claim_evidence SET claim_id=1 WHERE claim_id=3;',
                    'requires at least one evidence link')
        self.ok('UPDATE claims.claim_evidence SET evidence_id=2 WHERE claim_id=2;', writer=True)
        self.attack('UPDATE claims.claim_evidence SET evidence_id=999 WHERE claim_id=2;', '23503')
        self.attack('UPDATE claims.claim_evidence SET claim_id=999 WHERE claim_id=2;', '23503')
        self.orphan_count()

    def test_set_constraints_games(self):
        for mode in ('IMMEDIATE', 'DEFERRED'):
            self.attack('BEGIN; SET CONSTRAINTS ALL ' + mode + '; '
                        'DELETE FROM claims.claim_evidence WHERE claim_id=3; COMMIT;',
                        'requires at least one evidence link')
        self.attack('BEGIN; DELETE FROM claims.claim_evidence WHERE claim_id=3; '
                    'SET CONSTRAINTS ALL IMMEDIATE; COMMIT;', 'requires at least one evidence link')
        self.attack('BEGIN; SET CONSTRAINTS ALL IMMEDIATE; ' + insert() +
                    ' DELETE FROM claims.claim_evidence WHERE claim_id=99; COMMIT;',
                    'requires at least one evidence link')

    def test_evidence_exactly_one_and_enums(self):
        for parents in ('NULL,NULL', '1,1'):
            self.attack("INSERT INTO claims.evidence VALUES (99,%s,'computational','supports');" % parents,
                        '23514')
        self.attack("INSERT INTO claims.evidence VALUES (99,1,NULL,'invalid','supports');", '23514')
        self.attack("INSERT INTO claims.evidence VALUES (99,1,NULL,'computational','invalid');", '23514')
        self.attack(insert().replace("'OBSERVATION'", "'INVALID'"), '23514')

    def test_fk_restrict_as_owner(self):
        self.attack('DELETE FROM claims.evidence WHERE id=1;', '23503', writer=False)
        self.attack('DELETE FROM claims.claim WHERE id=1;', '23503', writer=False)
        self.attack(insert(evidence='ARRAY[999]::bigint[]'), '23503')
        self.attack(insert(rid=999), '23503')

    def test_confidence_groups(self):
        for value in ("'null'", "'1'", "'[]'", "'\"high\"'", "'{\"confidence\":1}'",
                      "'{\"score\":1}'", "'{\"unexpected\":1}'"):
            for group in ('bio', 'risk'):
                with self.subTest(group=group, value=value):
                    self.attack(insert(**{group: value}), '23514')
        for group, key in (('bio', 'replication'), ('risk', 'data_quality')):
            for nested in ('{"confidence":1}', '[{"score":1}]'):
                self.attack(insert(**{group: "'{\"%s\":%s}'" % (key, nested)}), '23514')
        self.ok(insert(bio="'{\"replication\":{\"count\":2}}'"), writer=True)
        self.orphan_count()

    def test_owner_registration_writer_claim_positive_control(self):
        functions = self.ok("SELECT p.proname, r.rolname, p.prosecdef, "
                            "array_to_string(p.proconfig, ';') FROM pg_proc p "
                            "JOIN pg_roles r ON r.oid=p.proowner "
                            "WHERE p.pronamespace='claims'::regnamespace "
                            "AND p.proname IN ('run_register','run_register_eligible') "
                            "ORDER BY p.proname;")
        self.assertEqual(functions.strip().splitlines(), [
            'run_register|gars_claims_owner|t|search_path=claims, pg_temp',
            'run_register_eligible|gars_claims_owner|t|search_path=claims, pg_temp'])
        registered = self.ok("SET ROLE gars_claims_owner; "
                             "SELECT claims.run_register_eligible(2,'q','p','h');")
        self.assertEqual(registered.strip().splitlines()[-1], '2')
        self.assertEqual(self.ok('SELECT exploratory FROM claims.run WHERE id=2;').strip(), 'f')
        self.assertEqual(self.ok(insert(rid=2), writer=True).strip().splitlines()[-1], '99')
        self.assertEqual(self.ok('SELECT run_id FROM claims.claim WHERE id=99;').strip(), '2')
        self.assertEqual(self.ok('SELECT evidence_id FROM claims.claim_evidence '
                                 'WHERE claim_id=99;').strip(), '1')
        self.orphan_count()

    def test_writer_registration_is_exploratory(self):
        registered = self.ok("SELECT claims.run_register(2,'q','p','h');", writer=True)
        self.assertEqual(registered.strip().splitlines()[-1], '2')
        self.assertEqual(self.ok('SELECT exploratory FROM claims.run WHERE id=2;',
                                 writer=True).strip().splitlines()[-1], 't')
        self.attack(insert(rid=2), 'exploratory run cannot produce a claim')
        self.attack('UPDATE claims.run SET exploratory=false WHERE id=2;', '42501')
        # Reusing an eligible ID must not replace or downgrade its owner binding.
        self.attack("SELECT claims.run_register(1,'q','p','h');", '23505')
        self.assertEqual(self.ok('SELECT exploratory FROM claims.run WHERE id=1;').strip(), 'f')
        self.attack("SELECT claims.run_register(3,'q','p','h',false);", '42883')

    def test_writer_cannot_register_eligible(self):
        self.attack("SELECT claims.run_register_eligible(2,'q','p','h');", '42501')
        self.attack("INSERT INTO claims.run VALUES (2,'q','p','h',false);", '42501')
        self.attack('UPDATE claims.run SET exploratory=false WHERE id=1;', '42501')

    def test_exploratory_refused(self):
        self.ok("INSERT INTO claims.run VALUES (2,'q','p','h',true);")
        self.attack(insert(rid=2), 'exploratory run cannot produce a claim')
        self.attack('UPDATE claims.run SET exploratory=false WHERE id=2;', '42501')

    def test_cold_twin_reapply_and_snapshot_binding(self):
        before = self.ok('SELECT claims.claims_export(1);')
        constraints = self.ok("SELECT conname, pg_get_constraintdef(oid) FROM pg_constraint "
                              "WHERE connamespace='claims'::regnamespace ORDER BY conname;")
        triggers = self.ok("SELECT tgname, pg_get_triggerdef(oid) FROM pg_trigger "
                           "WHERE tgrelid IN ('claims.claim'::regclass,'claims.claim_evidence'::regclass) ORDER BY oid;")
        p = self.sql(SCHEMA, transaction=True)
        self.assertNotEqual(p.returncode, 0)
        self.assertIn('claims schema already applied; re-apply refused', p.stderr)
        self.assertEqual(before, self.ok('SELECT claims.claims_export(1);'))
        self.assertEqual(constraints, self.ok("SELECT conname, pg_get_constraintdef(oid) FROM pg_constraint "
                              "WHERE connamespace='claims'::regnamespace ORDER BY conname;"))
        self.assertEqual(triggers, self.ok("SELECT tgname, pg_get_triggerdef(oid) FROM pg_trigger "
                           "WHERE tgrelid IN ('claims.claim'::regclass,'claims.claim_evidence'::regclass) ORDER BY oid;"))
        self.orphan_count()
        self.ok('DROP DATABASE IF EXISTS twin;', db='postgres')
        self.ok('CREATE DATABASE twin;', db='postgres')
        self.ok(SCHEMA, transaction=True, db='twin')
        self.ok((FIXTURE / 'fixture.sql').read_text(), transaction=True, db='twin')
        self.assertEqual(before, self.ok('SELECT claims.claims_export(1);', db='twin'))
        self.assertEqual(before.encode(), (FIXTURE / 'snapshot.json').read_bytes())

    def test_repeatable_read_cannot_orphan(self):
        sessions = []
        try:
            for evidence in (1, 3):
                p = subprocess.Popen(self.client(writer=True), env=row5.scrubbed_env(self.env),
                                     stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                                     universal_newlines=True, bufsize=1)
                sessions.append(p)
                p.stdin.write("SET statement_timeout=\'15s\'; BEGIN ISOLATION LEVEL REPEATABLE READ; "
                              "SELECT current_user = 'gars_claims_writer' AND NOT rolsuper "
                              "FROM pg_roles WHERE rolname = current_user; "
                              "DELETE FROM claims.claim_evidence WHERE claim_id=1 AND evidence_id=%s; "
                              "SELECT 'ready';\n" % evidence)
                p.stdin.flush()
                # Binary-free, unbuffered SQL output is consumed one line at a time.
                lines = []
                while True:
                    # The server statement_timeout bounds a blocked SQL command.
                    line = p.stdout.readline().strip()
                    self.assertTrue(line, 'writer session ended before ready')
                    lines.append(line)
                    if line == 'ready':
                        break
                self.assertIn('t', lines, 'attack principal is not the restricted writer')
            first_out, first_error = sessions[0].communicate('COMMIT;\n', timeout=60)
            self.assertEqual(sessions[0].returncode, 0, first_error)
            second_out, second_error = sessions[1].communicate('COMMIT;\n', timeout=60)
            self.assertNotEqual(sessions[1].returncode, 0)
            self.assertIn('40001', second_error)
        finally:
            for p in sessions:
                if p.poll() is None:
                    p.kill()
                p.communicate(timeout=60)
        self.orphan_count()

    def test_unsafe_existing_role_refused(self):
        cases = [
            ('ALTER ROLE gars_claims_writer CREATEROLE;', 'ALTER ROLE gars_claims_writer NOCREATEROLE;'),
            ('GRANT SET ON PARAMETER session_replication_role TO PUBLIC;',
             'REVOKE SET ON PARAMETER session_replication_role FROM PUBLIC;'),
            ('GRANT ALTER SYSTEM ON PARAMETER session_replication_role TO gars_claims_writer;',
             'REVOKE ALTER SYSTEM ON PARAMETER session_replication_role FROM gars_claims_writer;'),
            ("ALTER DATABASE source SET session_replication_role='REPLICA';",
             'ALTER DATABASE source RESET session_replication_role;'),
            ("ALTER ROLE gars_claims_writer SET session_replication_role=replica;",
             'ALTER ROLE gars_claims_writer RESET session_replication_role;'),
        ]
        for prepare, cleanup in cases:
            self.ok(prepare)
            try:
                p = self.sql(SCHEMA, transaction=True)
                self.assertNotEqual(p.returncode, 0)
                self.assertIn('unsafe pre-existing claims role', p.stderr)
            finally:
                self.ok(cleanup)
            self.orphan_count()

    def test_from_db_golden(self):
        out = self.tmp / 'report.md'
        p = run([sys.executable, GARS / '_system/claims/render_report.py', '--from-db', '1',
                 '--manifest', FIXTURE / 'manifest.json', '--out', out],
                env=row5.scrubbed_env(dict(self.env, PGUSER='gars_claims_writer')))
        self.assertEqual(p.returncode, 0, p.stderr)
        self.assertEqual(out.read_bytes(), (FIXTURE / 'report.md').read_bytes())
        self.orphan_count()


class ClaimEnvironmentTests(unittest.TestCase):
    def probe_case(self, ci, explicit, expected):
        def unavailable(cls):
            cls.probe = ('GARS_TEST_NO_CONTAINER=1' if explicit else 'docker info: exit 1')
        cleanup = mock.Mock()
        with mock.patch.dict(os.environ, {'CI': ci, 'GARS_TEST_NO_CONTAINER': explicit}), \
                mock.patch.object(row5.Row05DatabaseTests, 'setUpClass', classmethod(unavailable)), \
                mock.patch.object(row5.Row05DatabaseTests, 'tearDownClass', classmethod(lambda cls: cleanup())):
            with self.assertRaisesRegex(expected, 'GARS_TEST_NO_CONTAINER=1' if explicit else 'docker info'):
                ClaimConstraintTests.setUpClass()
            cleanup.assert_called_once()

    def test_explicit_no_container_precedes_ci(self):
        self.probe_case('true', '1', unittest.SkipTest)

    def test_runtime_failure_fails_ci(self):
        self.probe_case('true', '', AssertionError)

    def test_runtime_failure_skips_outside_ci(self):
        self.probe_case('', '', unittest.SkipTest)


if __name__ == '__main__':
    unittest.main(verbosity=2)
