#!/usr/bin/env python3
"""GARS-authored differential-expression wrapper — the ClawBio `rnaseq-de` replacement.

The ClawBio skill this retires produced three defects in one declared chaining pair, one
silent (decisions 0010, 0021): a complete, plausible DE table in which every gene was
anonymous. This wrapper owns the whole path instead — adaptation, PyDESeq2, figures, report —
with the output schema kept byte-compatible with the old skill's
(`gene,baseMean,log2FoldChange,pvalue,padj`; `run/tables/`, `run/figures/`, `adapted/`), so
projects produced by either path read the same downstream (decision 0029).

Division of labor, same as every 0028 wrapper: this file is stdlib-only and runs on stock
python; the analysis itself is a GENERATED script (`scripts/run_de.py`) executed under the
`gars-bio` environment via the generated `submit.sh` — a pure-Python DE step was SIGKILLed on
a login node once (decision 0005), so DE is sbatch work, always (decision 0027).

Subcommands:

  check    validates config (de.formula, de.contrast, compute.*) against the resolved counts
           and design: contrast levels present with >=2 samples each, formula terms are
           design columns, the counts matrix carries every design sample.
  prepare  re-validates, then writes scripts/run_de.py, submit.sh and the reproducibility
           bundle. Deterministic bytes.
  collect  the exit gate: de_results.csv exists, its FIRST column is `gene` with no empty
           identifiers (the 0010 defect class), padj present, every sample in the normalized
           matrix, all three figures and the report real. Writes OUTPUTS.tsv (de_results
           native, counts_gene adapted, gene_id_map native), STATUS, and returns the history
           entry (template version + model + which sub-stage supplied the counts).

Inputs `--counts` and `--design` are the PATHS the router resolved by artifact type
(_system/resolve_artifact.py) — this wrapper never searches for them itself.
"""

import argparse
import csv
import datetime
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
import workspace as ws          # noqa: E402
import wrapperlib as wl         # noqa: E402
from wrapperlib import (EXIT_OK, EXIT_FAILURE, EXIT_REFUSED, EXIT_USAGE,   # noqa: E402
                        emit, fail)

WORKSPACE = Path(__file__).resolve().parents[3]

ASSAY = "rnaseq_bulk"
SUBSTAGE = "02_rnaseq-de"

REQUIRED_KEYS = ("de.formula", "de.contrast", "compute.partition", "compute.time",
                 "compute.cpus", "compute.mem")

# The analysis, generated verbatim into scripts/run_de.py at prepare time. A template string
# rather than a shipped file so the wrapper is one self-contained unit and the script version
# is pinned by the template version in the manifest. Placeholders are filled by prepare; the
# script itself takes no arguments and embeds its exact inputs — reproducible by `python
# run_de.py` alone.
RUN_DE_TEMPLATE = '''#!/usr/bin/env python
"""Differential expression for {project}/{assay}, generated by the rnaseq-de wrapper.

Inputs, methods and outputs are frozen into this file by `prepare`; re-running it reproduces
the tables and figures exactly. Requires the gars-bio environment (pandas, pydeseq2,
scikit-learn, matplotlib).
"""
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

COUNTS = {counts!r}          # adapted matrix: `gene` identifier column, numeric sample columns
DESIGN = {design!r}
IDMAP = {idmap!r}
OUT = {out!r}
FORMULA = {formula!r}
FACTOR, NUMERATOR, DENOMINATOR = {factor!r}, {numerator!r}, {denominator!r}

# Method matched to the retired skill where the skill's method is reproducible, verified
# numerically against the leukemia-tall baseline (decision 0029): low-count filter >=10 in
# >=2 samples, round-then-int, refit_cooks. Tested genes, p-values, padj and the significant
# set are IDENTICAL to the baseline (padj r > 0.99998, 265/265 significant overlap).
#
# log2FoldChange is the DESeq2 Wald MLE, deliberately unshrunk. The retired skill published
# shrunken-looking LFCs from an estimator its own code cannot reproduce (its coefficient
# resolution returns empty for an A-vs-B contrast whose numerator is the design reference,
# and neither pydeseq2's MLE, apeglm on either coefficient sign, nor naive normalized ratios
# match its values). Rather than imitate an unidentifiable estimator, this publishes the
# documented DESeq2 default; effect directions and significance are unchanged.
MIN_COUNT, MIN_SAMPLES = 10, 2

counts = pd.read_csv(COUNTS, sep="\\t").set_index("gene")
design = pd.read_csv(DESIGN).set_index("sample_id")
counts = counts[design.index.tolist()]           # column order = design order, and a hard
                                                 # KeyError if any sample is missing
counts = counts[(counts >= MIN_COUNT).sum(axis=1) >= MIN_SAMPLES]

from pydeseq2.dds import DeseqDataSet
from pydeseq2.ds import DeseqStats

dds = DeseqDataSet(counts=counts.T.round().astype(int), metadata=design, design=FORMULA,
                   refit_cooks=True)
dds.deseq2()
stats = DeseqStats(dds, contrast=[FACTOR, NUMERATOR, DENOMINATOR])
stats.summary()

res = stats.results_df.copy()
res.index.name = "gene"

# Schema-compatible with the retired skill: gene,baseMean,log2FoldChange,pvalue,padj
out_tables = "%s/tables" % OUT
out_figures = "%s/figures" % OUT
import os
os.makedirs(out_tables, exist_ok=True)
os.makedirs(out_figures, exist_ok=True)
res.reset_index()[["gene", "baseMean", "log2FoldChange", "pvalue", "padj"]].to_csv(
    "%s/de_results.csv" % out_tables, index=False)

normed = pd.DataFrame(dds.layers["normed_counts"].T, index=counts.index,
                      columns=design.index)
normed.index.name = "gene"
normed.to_csv("%s/normalized_counts.csv" % out_tables)

# PCA on log2(normalized+1), top 500 most-variable genes (the retired skill's method)
logn = np.log2(normed + 1)
top = logn.loc[logn.var(axis=1).sort_values(ascending=False).head(500).index]
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
coords = pca.fit_transform(top.T.values)
fig, ax = plt.subplots(figsize=(6, 5))
for level, marker in zip(sorted(design[FACTOR].unique()), "osd^v<>"):
    sel = (design[FACTOR] == level).values
    ax.scatter(coords[sel, 0], coords[sel, 1], label=level, marker=marker)
for i, s in enumerate(design.index):
    ax.annotate(s, (coords[i, 0], coords[i, 1]), fontsize=7, alpha=0.7)
ax.set_xlabel("PC1 (%.1f%%)" % (100 * pca.explained_variance_ratio_[0]))
ax.set_ylabel("PC2 (%.1f%%)" % (100 * pca.explained_variance_ratio_[1]))
ax.legend(title=FACTOR)
fig.tight_layout(); fig.savefig("%s/pca.png" % out_figures, dpi=200); plt.close(fig)

sig = res.dropna(subset=["padj"])
fig, ax = plt.subplots(figsize=(6, 5))
ax.scatter(sig["log2FoldChange"], -np.log10(sig["pvalue"]), s=4, alpha=0.4,
           c=np.where(sig["padj"] < 0.05, "crimson", "grey"))
ax.set_xlabel("log2 fold change (%s vs %s)" % (NUMERATOR, DENOMINATOR))
ax.set_ylabel("-log10 p-value")
fig.tight_layout(); fig.savefig("%s/volcano.png" % out_figures, dpi=200); plt.close(fig)

fig, ax = plt.subplots(figsize=(6, 5))
ax.scatter(np.log10(res["baseMean"] + 1), res["log2FoldChange"], s=4, alpha=0.4,
           c=np.where(res["padj"].fillna(1) < 0.05, "crimson", "grey"))
ax.axhline(0, lw=0.8, color="black")
ax.set_xlabel("log10 mean expression"); ax.set_ylabel("log2 fold change")
fig.tight_layout(); fig.savefig("%s/ma_plot.png" % out_figures, dpi=200); plt.close(fig)

idmap = pd.read_csv(IDMAP, sep="\\t")
named = res.reset_index().merge(idmap, left_on="gene", right_on="gene_id", how="left")
n_sig = int((res["padj"] < 0.05).sum())
top10 = named.dropna(subset=["padj"]).nsmallest(10, "padj")
with open("%s/report.md" % OUT, "w") as fh:
    fh.write("# Differential expression: {project} ({assay})\\n\\n")
    fh.write("- Formula: `%s`\\n- Contrast: `%s,%s,%s` -- %s relative to %s\\n"
             % (FORMULA, FACTOR, NUMERATOR, DENOMINATOR, NUMERATOR, DENOMINATOR))
    fh.write("- Genes tested: %d\\n- Significant at padj < 0.05: %d\\n\\n"
             % (len(res), n_sig))
    fh.write("Top 10 by adjusted p-value:\\n\\n| gene | gene_name | log2FC | padj |\\n|---|---|---|---|\\n")
    for _, r in top10.iterrows():
        fh.write("| %s | %s | %.2f | %.2e |\\n"
                 % (r["gene"], r.get("gene_name", ""), r["log2FoldChange"], r["padj"]))
print("run_de: %d genes tested, %d significant" % (len(res), n_sig))
'''


def paths_for(project):
    return {"substage": project / "02_bioinformatics" / ASSAY / SUBSTAGE,
            "config": project / "_config" / ("%s.yaml" % ASSAY)}


def parse_contrast(cfg, fails):
    spec = cfg.get("de.contrast", "")
    parts = [p.strip() for p in spec.split(",")]
    if len(parts) != 3 or not all(parts):
        fails.append(fail("config", "de.contrast %r is not factor,numerator,denominator" % spec))
        return None
    return parts


def run_checks(project, counts_path, design_path):
    fails = []
    paths = paths_for(project)
    cfg = {}
    if not paths["config"].is_file():
        fails.append(fail("preconditions", "no config at _config/%s.yaml" % ASSAY))
    else:
        cfg = wl.read_config(paths["config"])
        wl.check_config_common(cfg, REQUIRED_KEYS, fails)

    design_rows = []
    if not Path(design_path).is_file():
        fails.append(fail("preconditions", "design table not found: %s" % design_path))
    else:
        with open(str(design_path)) as fh:
            design_rows = list(csv.DictReader(fh))
        if not design_rows:
            fails.append(fail("design", "design table is empty"))

    contrast = parse_contrast(cfg, fails) if cfg else None
    if contrast and design_rows:
        factor, num, den = contrast
        if factor not in design_rows[0]:
            fails.append(fail("design", "contrast factor %r is not a design column (%s)"
                              % (factor, ", ".join(design_rows[0]))))
        else:
            counts_by_level = {}
            for r in design_rows:
                counts_by_level.setdefault(r[factor], 0)
                counts_by_level[r[factor]] += 1
            for level in (num, den):
                if counts_by_level.get(level, 0) < 2:
                    fails.append(fail("design",
                                      "contrast level %r has %d sample(s) in the design; a "
                                      "tested level needs at least 2"
                                      % (level, counts_by_level.get(level, 0))))
        formula = cfg.get("de.formula", "")
        import re
        for term in re.findall(r"[A-Za-z_][A-Za-z0-9_]*", formula):
            if term not in design_rows[0]:
                fails.append(fail("config", "formula term %r is not a design column (%s)"
                                  % (term, ", ".join(design_rows[0]))))

    if not Path(counts_path).is_file():
        fails.append(fail("preconditions", "count matrix not found: %s" % counts_path))
    elif design_rows:
        header = open(str(counts_path)).readline().rstrip("\n").split("\t")
        missing = [r["sample_id"] for r in design_rows if r["sample_id"] not in header]
        if missing:
            fails.append(fail("counts", "count matrix lacks column(s) for design sample(s): "
                                        "%s" % ", ".join(missing)))
    return fails, cfg, paths


def cmd_check(args):
    project = Path(args.project)
    result = {"command": "check", "ok": False, "assay": ASSAY, "failures": []}
    if not project.is_dir():
        result["error"] = "no such project: %s" % project
        return emit(result, EXIT_USAGE)
    fails, cfg, paths = run_checks(project, args.counts, args.design)
    result["failures"] = fails
    result["ok"] = not fails
    return emit(result, EXIT_OK if result["ok"] else EXIT_FAILURE)


def cmd_prepare(args):
    project = Path(args.project)
    result = {"command": "prepare", "ok": False, "assay": ASSAY, "failures": []}
    if not project.is_dir():
        result["error"] = "no such project: %s" % project
        return emit(result, EXIT_USAGE)
    fails, cfg, paths = run_checks(project, args.counts, args.design)
    if fails:
        result["failures"] = fails
        result["error"] = "checks failed; nothing written. Run `check` for the same detail."
        return emit(result, EXIT_FAILURE)

    substage = paths["substage"]
    (substage / "scripts").mkdir(parents=True, exist_ok=True)
    (substage / "logs").mkdir(exist_ok=True)
    factor, num, den = parse_contrast(cfg, [])

    # Absolute paths throughout: submit.sh runs the script from run/, so anything relative
    # here resolves against the wrong directory (caught by the first validation job).
    adapted = (substage / "adapted").resolve()
    script = RUN_DE_TEMPLATE.format(
        project=project.resolve().name, assay=ASSAY,
        counts=str(adapted / "counts_gene.tsv"),
        design=str(Path(args.design).resolve()),
        idmap=str(adapted / "gene_id_to_name.tsv"),
        out=str((substage / "run").resolve()),
        formula=cfg["de.formula"], factor=factor, numerator=num, denominator=den)
    with ws.atomic_open(substage / "scripts" / "run_de.py") as fh:
        fh.write(script)

    # The adaptation runs first, in code (decision 0021): rename the identifier to `gene`,
    # drop gene_name into the id map, verify its own output header.
    body = """# 1) adapt the native matrix for the DE parser (decision 0021); stdlib python
python3 "$WS/_system/adapt_counts.py" \\
    --counts "{counts}" \\
    --out "{adapted}"

# 2) the analysis itself, under gars-bio (pandas, pydeseq2, scikit-learn, matplotlib)
"$GARS_PY" "{substage}/scripts/run_de.py" """.format(
        counts=str(Path(args.counts).resolve()), adapted=str(adapted.resolve()),
        substage=str(substage.resolve()))
    wl.write_submit_sh(substage, WORKSPACE, cfg, project.resolve().name,
                       "%s-de" % ASSAY, body)
    wl.write_reproducibility(substage, "rnaseq-de", WORKSPACE,
                             {"counts": Path(args.counts), "design": Path(args.design),
                              "config": paths["config"]},
                             [("formula", cfg["de.formula"]),
                              ("contrast", cfg["de.contrast"]),
                              ("counts", str(args.counts)), ("design", str(args.design))])

    result.update({"ok": True,
                   "wrote": ["scripts/run_de.py", "submit.sh",
                             "reproducibility/manifest.json", "reproducibility/commands.sh"],
                   "formula": cfg["de.formula"], "contrast": cfg["de.contrast"],
                   "submit": str((substage / "submit.sh").resolve())})
    return emit(result, EXIT_OK)


def cmd_collect(args):
    project = Path(args.project)
    result = {"command": "collect", "ok": False, "assay": ASSAY, "failures": []}
    if not project.is_dir():
        result["error"] = "no such project: %s" % project
        return emit(result, EXIT_USAGE)
    substage = paths_for(project)["substage"]
    if not (substage / "run" / ".gars_run_complete").is_file():
        result["error"] = ("run/.gars_run_complete is absent: the analysis has not finished "
                           "(or crashed before the marker). Check Slurm and the logs; collect "
                           "gates on completion, it does not wait for it.")
        return emit(result, EXIT_REFUSED)

    run = substage / "run"
    fails = []
    de = run / "tables" / "de_results.csv"
    if not de.is_file() or de.stat().st_size == 0:
        fails.append(fail("de_results", "missing or empty %s" % de))
    else:
        with de.open() as fh:
            rows = list(csv.reader(fh))
        # The 0010 defect class, checked as content: identifier column first, no anonymous rows.
        if not rows or rows[0][0] != "gene":
            fails.append(fail("de_results", "first column is %r, not 'gene' -- the identifier "
                                            "was dropped or renamed (decision 0010)"
                              % (rows[0][0] if rows else "missing")))
        elif any(not r[0].strip() for r in rows[1:]):
            fails.append(fail("de_results", "empty gene identifier(s) present -- a complete, "
                                            "plausible table of anonymous genes is exactly the "
                                            "silent failure this gate exists for"))
        if rows and "padj" not in rows[0]:
            fails.append(fail("de_results", "no padj column"))
        result["genes_tested"] = max(0, len(rows) - 1)

    normed = run / "tables" / "normalized_counts.csv"
    design_path = project / "01_samplesheets" / ("%s_design.csv" % ASSAY)
    if not normed.is_file():
        fails.append(fail("de_results", "missing %s" % normed))
    elif design_path.is_file():
        header = normed.open().readline().rstrip("\n").split(",")
        with design_path.open() as fh:
            samples = [r["sample_id"] for r in csv.DictReader(fh)]
        missing = [s for s in samples if s not in header]
        if missing:
            fails.append(fail("de_results", "normalized_counts.csv lacks sample(s): %s"
                              % ", ".join(missing)))

    for fig in ("pca.png", "volcano.png", "ma_plot.png"):
        p = run / "figures" / fig
        if not p.is_file() or p.stat().st_size == 0:
            fails.append(fail("figures", "missing or empty %s" % p))
    report = run / "report.md"
    if not report.is_file() or report.stat().st_size == 0:
        fails.append(fail("report", "missing or empty %s" % report))
    for name in ("counts_gene.tsv", "gene_id_to_name.tsv"):
        p = substage / "adapted" / name
        if not p.is_file() or p.stat().st_size == 0:
            fails.append(fail("adaptation", "missing or empty adapted/%s" % name))

    if fails:
        result["failures"] = fails
        return emit(result, EXIT_FAILURE)

    outputs = [("de_results", "native", "run/tables/de_results.csv"),
               ("counts_gene", "adapted", "adapted/counts_gene.tsv"),
               ("gene_id_map", "native", "adapted/gene_id_to_name.tsv")]
    with ws.atomic_open(substage / "OUTPUTS.tsv") as fh:
        fh.write("# type\trole\tpath\n")
        for typ, role, path in outputs:
            fh.write("%s\t%s\t%s\n" % (typ, role, path))

    now = datetime.datetime.now().strftime("%Y-%m-%dT%H:%M:%S")
    with ws.atomic_open(substage / "STATUS") as fh:
        fh.write("COMPLETE %s\n" % now)

    version = ws.template_version(WORKSPACE)
    model = args.model or "unknown"
    entry = "\n".join([
        "## <ISO-8601 date> — 02_bioinformatics/%s/%s — differential expression complete"
        % (ASSAY, SUBSTAGE),
        "",
        "Template version: %s" % version,
        "Model: %s" % model,
        "Method: PyDESeq2 via the gars rnaseq-de wrapper",
        "Counts supplied by: %s" % (args.counts_from or "unknown"),
        "Genes tested: %s" % result.get("genes_tested", "unknown"),
        "Outputs: " + ", ".join("`%s` (%s)" % (t, r) for t, r, _ in outputs),
    ])
    result.update({"ok": True,
                   "outputs": [{"type": t, "role": r, "path": p} for t, r, p in outputs],
                   "template_version": version, "model": model, "history_entry": entry})
    return emit(result, EXIT_OK)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    sub = ap.add_subparsers(dest="cmd")
    for name in ("check", "prepare"):
        p = sub.add_parser(name)
        p.add_argument("--project", required=True)
        p.add_argument("--counts", required=True,
                       help="the counts_gene path resolve_artifact.py returned")
        p.add_argument("--design", required=True,
                       help="the design path resolve_artifact.py returned")
    c = sub.add_parser("collect")
    c.add_argument("--project", required=True)
    c.add_argument("--model", default="unknown",
                   help="the exact model id of the agent executing this sub-stage (0024)")
    c.add_argument("--counts-from", default=None,
                   help="the sub-stage that supplied the counts, from the resolver")
    args = ap.parse_args(argv)
    if not args.cmd:
        ap.print_help(sys.stderr)
        return EXIT_USAGE
    return {"check": cmd_check, "prepare": cmd_prepare, "collect": cmd_collect}[args.cmd](args)


if __name__ == "__main__":
    sys.exit(main())
