#!/usr/bin/env python3
"""R-116/R-170: derive the frozen §17 rows and refuse incomplete release evidence.

Only existing evidence formats are read. Missing producers stay unmeasured; no
operator-supplied current-value or PASS override is accepted. Python 3.6 stdlib.
"""
import argparse
import datetime
from decimal import Decimal, InvalidOperation
from pathlib import Path
import re
import sys

REPO = Path(__file__).resolve().parents[1]
SPEC = 'docs/specs/GARS_Unified_Master_Guideline_v1.0.1_FINAL.md'
OUTPUT = 'docs/implementation/dod_current.md'
RESTORE = 'docs/ops/restore-log.md'


def clauses(root):
    text = (root / SPEC).read_text(encoding='utf-8')
    section = text.split('\n## 17. ', 1)[1].split('\n## 18. ', 1)[0]
    rows = []
    for line in section.splitlines():
        if line.startswith('| ') and not line.startswith('| Clause |'):
            # A literal pipe in a code span is not a table delimiter here.
            cells = [cell.strip() for cell in line.strip('|').split(' | ')]
            if len(cells) != 3:
                raise ValueError('unreadable specification table')
            rows.append(cells)
    if len(rows) != 13:
        raise ValueError('expected all thirteen §17 clauses')
    return rows


def restore_measurement(root):
    """Consume row 5's existing UTC CSV output, including FAIL records.

    Its four fields do not establish Node 1/off-machine/independent-canary
    provenance. Preserve that missing evidence rather than certify the full row.
    """
    path = root / RESTORE
    if not path.exists():
        return 'unmeasured', None, False
    records = []
    for line in path.read_text(encoding='utf-8').splitlines():
        if not re.match(r'^\d{4}-\d{2}-\d{2}', line):
            continue
        fields = [value.strip() for value in line.split(',')]
        if len(fields) != 4:
            raise ValueError('malformed restore output')
        stamp, rpo, rto, status = fields
        when = datetime.datetime.strptime(stamp, '%Y-%m-%dT%H:%M:%SZ').date()
        rpo, rto = Decimal(rpo), Decimal(rto)
        if not all(x.is_finite() and x >= 0 for x in (rpo, rto)) or status not in ('PASS', 'FAIL'):
            raise ValueError('invalid restore output')
        records.append((when, stamp, rpo, rto, status))
    if not records:
        return 'unmeasured', None, False
    when, stamp, rpo, rto, status = max(records, key=lambda row: row[1])
    value = '%s; RPO %s h; RTO %s min; %s; venue/canary unmeasured' % (stamp, rpo, rto, status)
    return value, when, False


def measurements(root, rows):
    values = {row[0]: ('unmeasured', None, False) for row in rows}
    values['restore drill'] = restore_measurement(root)
    # Existing benchmark runs measure tasks, not §17's sealed design catalogue,
    # reviewer sets, manifests, pilots or semantic mutants. Historical report
    # prose and producer-visible controls cannot fill those acceptance cells.
    return values


def render(rows, values):
    lines = ['# Definition of done — current evidence', '',
             'GENERATED by `python3 scripts/release_check.py`; do not edit cells.',
             'Clause, test and threshold are copied from frozen §17. Missing qualifying evidence is unmeasured.',
             '', '| Clause | Test | Threshold | Current value |', '|---|---|---|---|']
    for clause, test, threshold in rows:
        lines.append('| %s | %s | %s | %s |' % (clause, test, threshold, values[clause][0]))
    return '\n'.join(lines) + '\n'


def release_failures(values, today):
    errors = []
    for clause, (value, when, meets) in values.items():
        if when is None or 'unmeasured' in value:
            errors.append(clause + ': unmeasured')
        if not meets:
            errors.append(clause + ': threshold not established')
        if when is not None:
            age = (today - when).days
            if age > 14:
                errors.append(clause + ': older than 14 days')
            if age < 0:
                errors.append(clause + ': future evidence date')
    return errors


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='detect missing or hand-edited generated cells')
    parser.add_argument('--tag', action='store_true', help='release eligibility gate; does not create a Git tag')
    args = parser.parse_args(argv)
    try:
        rows = clauses(REPO)
        values = measurements(REPO, rows)
        expected = render(rows, values).encode('utf-8')
        output = REPO / OUTPUT
        # A tag check never silently repairs a hand-edited cell.
        if args.check or args.tag:
            if not output.is_file() or output.read_bytes() != expected:
                raise ValueError('DoD cells differ from regeneration (missing or hand-edited)')
            print('DoD cells verified: %d/%d byte-stable' % (len(rows), len(rows)))
        else:
            output.parent.mkdir(parents=True, exist_ok=True)
            output.write_bytes(expected)
            print('DoD cells regenerated: %d/%d' % (len(rows), len(rows)))
        if args.tag:
            errors = release_failures(values, datetime.datetime.utcnow().date())
            if errors:
                for error in errors:
                    print('release tag: REFUSED (%s)' % error)
                return 1
            print('release tag: eligible')
        return 0
    except (OSError, ValueError, IndexError, InvalidOperation) as exc:
        print('release check: REFUSED (%s)' % exc, file=sys.stderr)
        return 1


if __name__ == '__main__':
    sys.exit(main())
